### ISSUE TITLE
iOS  Framework 'opencv_dart' not found

### ISSUE THREAD

**Issue by psguny9me** [rainyl/opencv_dart#103]
Error (Xcode): Framework 'opencv_dart' not found

Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)

 I am encountering this error. Is there a solution?

**Comment by mehmetnuriaydin** [comment]
I am encountering this error too. I'm looking for any solution.

**Comment by psguny9me** [comment]
> I am encountering this error too. I'm looking for any solution.

I solved this issue.

I installed 'homebrew' and 'wget'.

Try it now.

**Comment by psguny9me** [comment]
I solved this issue.

I installed homebrew and wget.

Try it now.

**Comment by rainyl** [comment]
https://github.com/rainyl/opencv_dart/blob/b71f6d1dd01f62b91cfa4b4e2340fc4bdd7510c4/ios/Makefile#L27

Yes, make sure that you have wget, tar and make installed

And, please fowllow the message `Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)` to add -v to show more detailed messages if you have problems.

AND, you guys didn't follow the question template, closed.

**Comment by mehmetnuriaydin** [comment]
I installed wget, tar, make.

It's solved.

I tested opencv_dart 1.0.9 on ios 17.4 simulator, it's works.

Thanks so much @psguny9me and @rainyl
