### ISSUE TITLE
operating system string maybe wrong

### ISSUE THREAD

**Issue by YancyHsu** [rainyl/opencv_dart#107]
https://github.com/rainyl/opencv_dart/blob/dcb17be2fa6e26add0f8144ba919d7bfe43972d5/bin/setup_commands.dart#L41

here maybe linux

**Comment by rainyl** [comment]
Oh!!!, Yes it's wrong, will be corrected soon, thanks a lot!

But it won't affect most users because the script is only used for manual setup now, auto setup is the default one, so no new version on pub.dev. If you personally needs it please tell me and I will publish a hotfix version.

**Comment by YancyHsu** [comment]
i cant run on linux, so i tried the manual setup, i have another issue for linux run. thanks!
