### ISSUE TITLE
Error: CMake 3.18 or higher is required on Linux

### ISSUE THREAD

**Issue by YancyHsu** [rainyl/opencv_dart#109]
https://github.com/rainyl/opencv_dart/blob/dcb17be2fa6e26add0f8144ba919d7bfe43972d5/linux/CMakeLists.txt#L4

my system cmake version is :
linux cmd>> cmake --version
result>> cmake version 3.29.6

but when run this line above, it throws:
CMake 3.18 or higher is required.  You are running version 3.16.3

i add this line in this CmakeLists.txt, it shows:
add in CmakeLists.txt>> message(WARNING "----${CMAKE_VERSION}")
result>> ----3.16.3

i cant find what is wrong

**Comment by YancyHsu** [comment]
add in CmakeLists.txt>> message(WARNING "----${CMAKE_ROOT}")
then I got:
>> ----/snap/flutter/145/usr/share/cmake-3.16

so the flutter itself use 3.16

**Comment by rainyl** [comment]
- https://github.com/canonical/flutter-snap/issues/53

Download and install flutter manually, do not use snap.

**Comment by rainyl** [comment]
It requires a minimum cmake verson of 3.18 because file(ARCHIVE_EXTRACT) is only available since 3.18, https://cmake.org/cmake/help/latest/command/file.html#archive-extract

**Comment by YancyHsu** [comment]
> It requires a minimum cmake verson of 3.18 because file(ARCHIVE_EXTRACT) is only available since 3.18, https://cmake.org/cmake/help/latest/command/file.html#archive-extract

get it, tks

**Comment by YancyHsu** [comment]
> It requires a minimum cmake verson of 3.18 because file(ARCHIVE_EXTRACT) is only available since 3.18, https://cmake.org/cmake/help/latest/command/file.html#archive-extract

it works, and tips tell me install ninja, gtk, pkg-config, clang
