### ISSUE TITLE
Using imencode and Mat.fromList throws error

### ISSUE THREAD

**Issue by arozdorozhniuk** [rainyl/opencv_dart#111]
## Question
When trying to use imencode function I keep getting error:

Usage:
`imageData` is Uint8List representing jpeg image.
`final mat = imdecode(imageData, IMREAD_UNCHANGED);`

Error:
`[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to lookup symbol 'VecUChar_NewFromPointer': dlsym(RTLD_DEFAULT, VecUChar_NewFromPointer): symbol not found`

Also I've tried to convert Uint8List to Mat using Mat.fromList constructor, but it throws an error as well.

Usage:
`final mat = Mat.fromList(height, width, MatType.CV_8UC1, imageData.toList());`

Error:
`[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to lookup symbol 'Mat_NewFromBytes': dlsym(RTLD_DEFAULT, Mat_NewFromBytes): symbol not found`

I'm not getting it. Is something wrong with my bytelist or it its something with implementation of those methods?

**Comment by rainyl** [comment]
Looks like your dynamic library is broken, please update to the newest version or run setup manually with -f flag to overwrite the existed library and try again.

**Comment by arozdorozhniuk** [comment]
It was so easy.. OMG, thank you!

**Comment by rainyl** [comment]
Never mind~
