### ISSUE TITLE
Failed to load dynamic library

### ISSUE THREAD

**Issue by h1tmd** [rainyl/opencv_dart#12]
I have just finished compiling the dll for Windows through the README but the following error still shows up whenever I run a program;
`Invalid argument(s): Failed to load dynamic library 'opencv_dart.dll': The specified module could not be found.
   (error code: 126)`
What do I do next? How do I run it properly or add it to Flutter/Dart?

**Comment by rainyl** [comment]
Add the path of `opencv_dart.dll` to your PATH environment variable.

If you intend to use for a flutter project, after compiled, opencv_dart.dll should be copied to `windows` directory of opencv_dart, and you just need to add opencv_dart to your flutter project dependencies. see more detailes in `example`

**Comment by rainyl** [comment]
This is not the problem of `opencv_dart` itself, closing.
