### ISSUE TITLE
Async features2d

### ISSUE THREAD

**Issue by rainyl** [rainyl/opencv_dart#122]
Async features2d

- [ ] C wrappers
- [ ] dart bindings
- [ ] tests

**Comment by rainyl** [comment]
@abdelaziz-mahdy Are you interested in this module?

**Comment by abdelaziz-mahdy** [comment]
Since all the modules are the same, I think when I start working on a module I assign it , or comment that I will be working on it ? So we organize tasks without wasting time 

Like it it's taken by you I will do something the same for you I guess that's clearer

**Comment by rainyl** [comment]
Agree.

**Comment by abdelaziz-mahdy** [comment]
question 
file have header of 
`/* Created by Rainyl. Licensed: Apache 2.0 license. Copyright (c) 2024 Rainyl. */`
i kept using it when i created files, should i write my own name?

**Comment by rainyl** [comment]
> question file have header of `/* Created by Rainyl. Licensed: Apache 2.0 license. Copyright (c) 2024 Rainyl. */` i kept using it when i created files, should i write my own name?

Add your name please, your efforts should be respected!
