### ISSUE TITLE
Async Contrib

### ISSUE THREAD

**Issue by rainyl** [rainyl/opencv_dart#124]
Async Contrib

- [x] C wrappers
- [x] dart bindings
- [x] tests

**Comment by rainyl** [comment]
@abdelaziz-mahdy And this module?

**Comment by abdelaziz-mahdy** [comment]
i will be taking a rest today, since i have alot of stuff to do, when i free sometime will be back to do this one ok?

just letting you know incase you want to start it

**Comment by rainyl** [comment]
Sure, have a nice day, thanks!
