### ISSUE TITLE
memory leak in v1.0.10

### ISSUE THREAD

**Issue by gotecq-thudang** [rainyl/opencv_dart#136]
Memory leak and crash app when i run function detectMarker in version 1.0.10
But in this version, everything work:
`opencv_dart:
    git:
      url: https://github.com/rainyl/opencv_dart
      ref: 96a936a`
      
This is code:
`   final img = cv.imread(arucoImage6x6_250);
    expect(img.isEmpty, false);

    final dict = cv.ArucoDictionary.predefined(cv.PredefinedDictionaryType.DICT_6X6_250);
    final params = cv.ArucoDetectorParameters.empty();
    final detector = cv.ArucoDetector.create(dict, params);

    final (_, ids, _) = detector.detectMarkers(img);
    expect(ids, isNotEmpty);

    dict.dispose();
    params.dispose();
    img.dispose();
    detector.dispose();`

Hope you could help.

**Comment by rainyl** [comment]
Didn't reproduce it, worked as expected.

```dart
import 'package:opencv_dart/opencv_dart.dart' as cv;

void main(List<String> args) {
  for (int i = 0; i < 100000; i++) {
    final img = cv.imread("test/images/aruco_6X6_250_6.png");

    final dict = cv.ArucoDictionary.predefined(cv.PredefinedDictionaryType.DICT_6X6_250);
    final params = cv.ArucoDetectorParameters.empty();
    final detector = cv.ArucoDetector.create(dict, params);

    final (_, ids, _) = detector.detectMarkers(img);

    dict.dispose();
    params.dispose();
    img.dispose();
    detector.dispose();
  }
}
```

```bash
dart run --pause-isolates-on-start --observe .\test.dart
```

Memory consumption:

![image](https://github.com/rainyl/opencv_dart/assets/30213663/08f82030-9b7a-4fc9-bd0c-fe9c0edc2b8c)

If you are sure it occurs, please provide detailed steps to reproduce.

**Comment by rainyl** [comment]
No further informations, I am going to close this issue, feel free to reopen it if you have more info.
