### ISSUE TITLE
opencv_dart make fail,used opencv4.9.0 android ,but still fail in link

### ISSUE THREAD

**Issue by chennankuan** [rainyl/opencv_dart#14]
[14/16] Building CXX object CMakeFiles/opencv_dart.dir/C_/Users/chen/go/pkg/mod/gocv.io/x/gocv@v0.35.0/core.cpp.o
  [15/16] Building CXX object CMakeFiles/opencv_dart.dir/C_/Users/chen/go/pkg/mod/gocv.io/x/gocv@v0.35.0/videoio.cpp.o
  [16/16] Linking CXX shared library D:\flutter_projects\flutter_nav_menu\build\app\intermediates\cxx\Debug\5z2f1i14\obj\arm64-v8a\libopencv_dart.so

  FAILED: D:/flutter_projects/flutter_nav_menu/build/app/intermediates/cxx/Debug/5z2f1i14/obj/arm64-v8a/libopencv_dart.so 
  cmd.exe /C "cd . && D:\android_studio_sdk\ndk\23.1.7779620\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=aarch64-none-linux-android21 --sysroot=D:/android_studio_sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/windows-x86_64/sysroot -fPIC -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fexceptions -frtti -stdlib=libc++ -g  -fno-limit-debug-info  -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--fatal-warnings -Qunused-arguments -Wl,--no-undefined -shared -Wl,-soname,libopencv_dart.so -o D:\flutter_projects\flutter_nav_menu\build\app\intermediates\cxx\Debug\5z2f1i14\obj\arm64-v8a\libopencv_dart.so @CMakeFiles\opencv_dart.rsp  && cmd.exe /C "cd /D D:\flutter_projects\flutter_nav_menu\android\app\.cxx\Debug\5z2f1i14\arm64-v8a && D:\android_studio_sdk\cmake\3.18.1\bin\cmake.exe -E copy_if_different D:/flutter_projects/flutter_nav_menu/build/app/intermediates/cxx/Debug/5z2f1i14/obj/arm64-v8a""
  CMake Error: cmake version 3.22.1-g37088a8-dirty
  Usage: D:\android_studio_sdk\cmake\3.18.1\bin\cmake.exe -E <command> [arguments...]

  ninja: build stopped: subcommand failed.

  C++ build system [build] failed while executing:
      @echo off
      "D:\\android_studio_sdk\\cmake\\3.18.1\\bin\\ninja.exe" ^
        -C ^
        "D:\\flutter_projects\\flutter_nav_menu\\android\\app\\.cxx\\Debug\\5z2f1i14\\arm64-v8a" ^
        opencv_dart
    from D:\flutter_projects\flutter_nav_menu\android\app

**Comment by rainyl** [comment]
Seems you didn't follow my build instructions, this project has removed dependency of gocv since v0.6.4, so I don't know why you have such information `Building CXX object CMakeFiles/opencv_dart.dir/C_/Users/chen/go/pkg/mod/gocv.io/x/gocv@v0.35.0/core.cpp.o`. 
If you are expert in cmake and didn't follow my build instructions, please fix it your self, I have no time to solve your problem.
If you want to build this project yourself, see more in workflow files, closing.
