### ISSUE TITLE
How can i find similarity percent/value for different 2 image/video with this package for Flutter?

### ISSUE THREAD

**Issue by PBomermustekiin** [rainyl/opencv_dart#146]
**Read README carefully first**
**Star :star: this project if you want to ask a question, no star, no answer**

## Question
I want to compile 2 image or video and get that assets similarity percent or value. How can i do that with this package? I read that sources already. Any suggestion except that ones?

https://stackoverflow.com/questions/72341447/compare-photos-and-choose-the-most-similar

https://stackoverflow.com/questions/11541154/checking-images-for-similarity-with-opencv

**Comment by rainyl** [comment]
Take a look at img hash module of opencv.

https://docs.opencv.org/4.10.0/d4/d93/group__img__hash.html

If it doesn't meet your requirements, you need to development your own comparison algorithms.

**Comment by PBomermustekiin** [comment]
.
