### ISSUE TITLE
Does this version do not support set ROI feature？If support how can I use it？

### ISSUE THREAD

**Issue by ykwang** [rainyl/opencv_dart#151]
**Read README carefully first**
**Star :star: this project if you want to ask a question, no star, no answer**

## Question
Describe the question here

**Comment by ykwang** [comment]
I want to set a ROI in a image,and copy the other image into the ROI,
because  seting the  value one by one  takes a long time.

**Comment by rainyl** [comment]
Take a look at https://github.com/rainyl/opencv_dart/blob/f9f934fa21329216e509216b9f7d43ea2016a73d/lib/src/core/mat.dart#L1173-L1175

But this API will be deprecated, use copyTo(Mat img, {Mat? mask}) in the future version
