### ISSUE TITLE
MAT to and from list 

### ISSUE THREAD

**Issue by abdelaziz-mahdy** [rainyl/opencv_dart#164]
i found to list for mat object, do you think a from list should be added? it will make it easier to convert to dart and from dart objects to send objects between isolates

**Comment by rainyl** [comment]
Actually Mat.fromList was already supported, please check it in mat.dart, and recently i added Mat.fromVec, which also supports create Mat from a wrapped vector.

And, the current implementation of Mat.tolist is not elegant, i am considering constructing vectors from c++ in the future.

**Comment by abdelaziz-mahdy** [comment]
Oh looks like I missed it then, anyway I wanted to use to send data across isolates 


Also, imencodeasync returns bool,unilist 
Why it's not the same as imencode

**Comment by abdelaziz-mahdy** [comment]
`factory Mat.fromList(int rows, int cols, MatType type, List<num> data);`
  
is there an option to take the output of tolist and just create a mat from it ? since i think this doesnt handle 2d arrays

**Comment by rainyl** [comment]
First of all, sorry for the late reply, I am kind of busy recently.

> Also, imencodeasync returns bool,unilist Why it's not the same as imencode

Actually `imencode` should return `(bool, Mat)` too, same as **opencv-python**, but I forgot it when developing the sync APIs ...😭

![image](https://github.com/user-attachments/assets/73c1f6c4-fc48-4869-9a26-091f864e839b)

So maybe we can fix it in the next release? Afterall, so many breaking changes will be included in the next release.

Or you think we should keep the current status and keep compatibility?

> is there an option to take the output of tolist and just create a mat from it ? since i think this doesnt handle 2d arrays

Yes, `Mat.fromList` only accepts 1D List for now, I have reviewed #165, thanks for your contribution!

**Comment by abdelaziz-mahdy** [comment]
> First of all, sorry for the late reply, I am kind of busy recently.
> 
> > Also, imencodeasync returns bool,unilist Why it's not the same as imencode
> 
> Actually `imencode` should return `(bool, Mat)` too, same as **opencv-python**, but I forgot it when developing the sync APIs ...😭
> 
> ![image](https://private-user-images.githubusercontent.com/30213663/350907953-73c1f6c4-fc48-4869-9a26-091f864e839b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NDAyMjYsIm5iZiI6MTcyMTYzOTkyNiwicGF0aCI6Ii8zMDIxMzY2My8zNTA5MDc5NTMtNzNjMWY2YzQtZmM0OC00ODY5LTlhMjYtMDkxZjg2NGU4MzliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDA5MTg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlYzk5NzU3NDE1ZDVmOWZiN2M4ZTIzZTBhYzhiOGYyYWE2NTNjMjE3YzE1NzFmNWUyZDUwNWZmYTM0NGNiNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YIGl6ukEwBNDDtCM86pd2pdatYZ3ZQX-Yt1iDv-N7kw)
> 
> So maybe we can fix it in the next release? Afterall, so many breaking changes will be included in the next release.
> 
> Or you think we should keep the current status and keep compatibility?
> 
> > is there an option to take the output of tolist and just create a mat from it ? since i think this doesnt handle 2d arrays
> 
> Yes, `Mat.fromList` only accepts 1D List for now, I have reviewed #165, thanks for your contribution!

dont worry, i get busy and forget to reply too,

anyway i am confused what does the bool do is that success or failure? and i think matching to the python api will be much easier for developers so i think that breaking change is needed

**Comment by sysmesh** [comment]
Hope i'm not hi-jacking the thread but I am trying to use the Mat.fromVec function and it causes the app to crash (on both iOS simulator and physical iphone device). 
Can you please explain what is the difference between a Vector and a Wrapped Vector?

The following line: 
penCV.Mat docCntMat = openCV.Mat.fromVec(docCnt!);

Casues the crash. docCnt is Mat.Vec type. 

Any idea/advice?

Thanks!

**Comment by rainyl** [comment]
> Hope i'm not hi-jacking the thread but I am trying to use the Mat.fromVec function and it causes the app to crash (on both iOS simulator and physical iphone device). Can you please explain what is the difference between a Vector and a Wrapped Vector?
> 
> The following line: penCV.Mat docCntMat = openCV.Mat.fromVec(docCnt!);
> 
> Casues the crash. docCnt is Mat.Vec type.
> 
> Any idea/advice?
> 
> Thanks!

Attach your error logs please, also, better to provide a minimum reproducable example.

**Comment by abdelaziz-mahdy** [comment]
Also I think a new issue will be better for tracking the status
