### ISSUE TITLE
Platform Exception

### ISSUE THREAD

**Issue by PavanInfiplus** [rainyl/opencv_dart#177]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: CvException(code: -215, err: , msg:OpenCV(4.10.0) /home/runner/work/opencv.full/opencv.full/build/opencv/modules/core/src/matrix.cpp:452: error: (-215:Assertion failed) total() == 0 || data != NULL in function 'Mat'
 
 When i run example app in this package cant able to run the results

**Comment by rainyl** [comment]
Please clean your cache and try again, or just re-clone and run again.
