### ISSUE TITLE
video writer open (sync vs async)

### ISSUE THREAD

**Issue by abdelaziz-mahdy** [rainyl/opencv_dart#197]
sync returns video Writer 
https://github.com/rainyl/opencv_dart/blob/cb044565f983a51ce3ed4923b6298df38538c2d4/lib/src/video/videoio.dart#L174
async returns bool 
https://github.com/rainyl/opencv_dart/blob/cb044565f983a51ce3ed4923b6298df38538c2d4/lib/src/video/videoio_async.dart#L102

cant figure which one is the correct api

**Comment by rainyl** [comment]
Oh, it's redundant, https://github.com/rainyl/opencv_dart/blob/cb044565f983a51ce3ed4923b6298df38538c2d4/lib/src/video/videoio.dart#L174-L218

maybe we should rename `factory open()` to something like `openFile`

**Comment by rainyl** [comment]
the open and openAsync should be class methods (wrapper for https://docs.opencv.org/4.x/dd/d9e/classcv_1_1VideoWriter.html#a8b44d21f9bb5a02f531b50bbb15b9527)
