### ISSUE TITLE
Got it working on simulator, issue on real device - what am I missing?

### ISSUE THREAD

**Issue by xonaman** [rainyl/opencv_dart#200]
Hey!

I am using version 1.2.1 and got everything working on the simulator (iOS).

When building for release and running that on a real device (iOS), I encounter the following issue:

`Invalid argument(s): Failed to lookup symbol 'Image_IMRead_Async': dlsym(RTLD_DEFAULT, Image_IMRead_Async): symbol not found`

I have looked into https://github.com/rainyl/opencv_dart/issues/144 and can confirm that `opencv_dart.xcframework` exists in `~/.pub-cache/hosted/pub.dev/opencv_dart-1.2.1/ios`.

I think there must be some setting that I need to enable to make the libs shipping with the release build.

Can anyone help?

**Comment by rainyl** [comment]
@xonaman hello.

could you please take a look at whether the symbol is exists, you can refer to https://github.com/rainyl/opencv_dart/issues/24#issuecomment-2047320726

**Comment by xonaman** [comment]
I assume you mean `symbols opencv_dart | grep IMRead`. Here’s the output:

```
~/.pub-cache/hosted/pub.dev/opencv_dart-1.2.1/ios/opencv_dart.framework % symbols opencv_dart | grep IMRead
                0x000000000009a9b0 (   0x2f0) Image_IMRead [FUNC, EXT, NameNList, MangledNameNList, Merged, NList, FunctionStarts] 
                0x000000000009c460 (   0x340) Image_IMRead_Async [FUNC, EXT, NameNList, MangledNameNList, Merged, NList, FunctionStarts]
```

**Comment by rainyl** [comment]
Yes, it is.

did you run setup manually? since i see 'opencv_dart.framework', it should be 'opencv_dart.xcframework', and there should be two subdirectory in it, arm64 for real device and x86_64 for simulator, cd to arm64 and run 'symbols opencv_dart | grep IMRead', and then tell me the result please.

I do not use iPhone so can't test it by myself, what i can help is give you the possible solution, hope you won't be bored.

**Comment by rainyl** [comment]
@xonaman The correct structure of `~/.pub-cache/hosted/pub.dev/opencv_dart-1.2.1/ios` should be like:

![image](https://github.com/user-attachments/assets/2d4cfb9b-4259-49a0-a357-c806e9cbbb24)

you can try to run setup manually with `dart run opencv_dart:setup ios -a os64 -f` and try again

**Comment by xonaman** [comment]
@rainyl After `dart run opencv_dart:setup ios -a os64 -f`, my `~/.pub-cache/hosted/pub.dev/opencv_dart-1.2.1/ios` looks like this:

```
robertmainzer@MacBook-Pro-2 ios % find .                          
.
./Makefile
./opencv_dart.framework
./opencv_dart.framework/opencv_dart
./opencv_dart.framework/Info.plist
./libopencv_dart-ios-os64.tar.gz
./opencv_dart.xcframework
./opencv_dart.xcframework/ios-x86_64-simulator
./opencv_dart.xcframework/ios-x86_64-simulator/opencv_dart.framework
./opencv_dart.xcframework/ios-x86_64-simulator/opencv_dart.framework/opencv_dart
./opencv_dart.xcframework/ios-x86_64-simulator/opencv_dart.framework/Info.plist
./opencv_dart.xcframework/ios-arm64
./opencv_dart.xcframework/ios-arm64/opencv_dart.framework
./opencv_dart.xcframework/ios-arm64/opencv_dart.framework/opencv_dart
./opencv_dart.xcframework/ios-arm64/opencv_dart.framework/Info.plist
./opencv_dart.xcframework/Info.plist
./opencv_dart.podspec
```

I build with that again using `flutter build ipa --release` and still the error occurs.

**Comment by rainyl** [comment]
https://github.com/rainyl/opencv_dart/actions/runs/10259385478/job/28383772890?pr=204#step:5:116

I have no apple devices so can't test it, but it seems every thing is okay in the above logs.

not sure why.

**Comment by abdelaziz-mahdy** [comment]
may that help? i found it on tflite repo 
<img width="809" alt="image" src="https://github.com/user-attachments/assets/deed7a54-e716-4bde-bc48-571d0770dab3">

i see that they show in the action logs, but maybe they get stripped somehow on running on device?

**Comment by rainyl** [comment]
> may that help? i found it on tflite repo 
> <img width="809" alt="image" src="https://github.com/user-attachments/assets/deed7a54-e716-4bde-bc48-571d0770dab3">
> 
> i see that they show in the action logs, but maybe they get stripped somehow on running on device?

I think so.

**Comment by rainyl** [comment]
No response for a long time, I am going to close this issue, feel free to reopen it again if anyone still have more problems.

For the solution, please check the advice posted by abdelaziz-mahdy https://github.com/rainyl/opencv_dart/issues/200#issuecomment-2277701671, I cant test it.

**Comment by kreazyme** [comment]
I got the same problems :( 
Device: Mac M1 14.4 Simulator
opencv_dart: ^1.2.1
3.24.0 Flutter SDK

**Comment by rainyl** [comment]
@kreazyme try to set the strip style,  https://docs.flutter.dev/platform-integration/ios/c-interop#stripping-ios-symbols

**Comment by kreazyme** [comment]
Finnaly, I try to ```run opencv_dart:setup``` and ```flutter clean && flutter pub get``` and it's worked well

**Comment by abdelaziz-mahdy** [comment]
> @kreazyme try to set the strip style,  https://docs.flutter.dev/platform-integration/ios/c-interop#stripping-ios-symbols

I think that should be added to readme, to avoid the problem in the future

**Comment by rainyl** [comment]
> I think that should be added to readme, to avoid the problem in the future

Agree, and a Q&A section is necessary.

**Comment by xonaman** [comment]
@abdelaziz-mahdy your solution worked in my case. Thank you so much!

**Comment by abdelaziz-mahdy** [comment]
glad to help <3

**Comment by abdelaziz-mahdy** [comment]
> I've tried all the solutions, but hadn't have success. Tried to run `opencv_dart:setup` and `flutter clean` && `flutter pub get` many of many times without any success. **How to solve this issue?** Thank you in advance!
> ![screenshot-20-09-2024-13-40-32](https://github.com/user-attachments/assets/c205891c-5d99-47dc-88f1-25fec74392bd)
> ![screenshot-20-09-2024-13-42-17](https://github.com/user-attachments/assets/7206c4e7-3db4-44cb-8d5c-542d418b118e)
> ![screenshot-20-09-2024-13-42-49](https://github.com/user-attachments/assets/e60a9112-5286-4499-9154-7bc660e637ec)
> ![screenshot-20-09-2024-13-43-13](https://github.com/user-attachments/assets/714a6a01-71e9-4d8d-912e-b9644541dfa3)
> 
> 

Your issue is different, increase your minimum os version and it should work correctly

**Comment by rainyl** [comment]
@frg-x Get it, I am working on it.

**Comment by fpcxsun** [comment]
> 我已经尝试了所有的解决方案，但没有成功。尝试运行并& & 多次，但没有任何成功。**如何解决这个问题？**提前感谢您！`opencv_dart:setup``flutter clean``flutter pub get` 

Finally, I solved it!

<img width="551" alt="Image" src="https://github.com/user-attachments/assets/e52c94a7-5b91-4579-b30f-df4d97d58455" />
