### ISSUE TITLE
Q&A

### ISSUE THREAD

**Issue by rainyl** [rainyl/opencv_dart#212]
### 1. used environment variables
- [x] `OPENCV_DART_DISABLE_AUTO_BUILD` if set, prebuilt libs will not be downloaded
- [x] `OPENCV_DART_ANDROID_ENABLED_ABI` #211 
  - e.g., `export OPENCV_DART_ANDROID_ENABLED_ABI="arm64-v8a,armeabi-v7a"` and then `x86_64` will not be downloaded or will be deleted if exist, will be useful if you want to build apk for specific platforms
- [x] `OPENCV_DART_LIB_PATH` ONLY for debug or test, if set, library will be loaded from it.

### 2. libopencv_dart.so/.dll/.framework/.dylib not found
  - for windows, check whether the `opencv_dart.dll` exists, typically it should exists in `~\AppData\Local\Pub\Cache\hosted\pub.dev\opencv_dart-<version>\windows`
  - for linux, check whether `libopencv_dart.so` exists, `~/.pub-cache/hosted/pub.dev/opencv_dart-<version>/linux`
  - for macos, check `~/.pub-cache/hosted/pub.dev/opencv_dart-<version>/macos`
  - for ios, check `opencv_dart.xcframework`, https://github.com/rainyl/opencv_dart/issues/200#issuecomment-2264409315
  - for android, check `android/src/main/jniLibs`
### 5. instructions for cache cleaning up, manual setup
  - You can run manual setup if the auto setup doesn't work, pass `-f` option to overwrite existed files, e.g., `dart run opencv_dart:setup android -a arm64-v8a -f`
### 6. video https://github.com/rainyl/opencv_dart/issues/159#issuecomment-2238065384

**Comment by hanan0007** [comment]
can i use this package to find the similar images ?

**Comment by rainyl** [comment]
> can i use this package to find the similar images ?

Theoretically, yes. You can use this package to do anything that opencv can do.

Remember to open new issues instead of replying to this one if you have more questions.
