### ISSUE TITLE
libopencv_dart.so not found

### ISSUE THREAD

**Issue by thormj** [rainyl/opencv_dart#23]
I made a test app, copied the example into main.dart, and when I ran it, I get a red screen of death saying library link failed -- "libopencv_dart.so not found"

Do I need another file in the project somewhere?

**Comment by rainyl** [comment]
why can't you read README carefully, take a look at IMPORTANT section in README

**Comment by thormj** [comment]
I didn't see it because I came from pub.dev and pub.dev didn't mention it.
Then I tried it for android all at once and... it still failed on my Galaxy 21.
Then I did each of everything and the ios (since eventually it will go to iPhones), and now it works.

Took an age to install, but I get the details.  Now to play with OpenCV and see what I can do...

**Comment by rainyl** [comment]
Well, It's because the support of native code distribution of dart is really annoying, maybe it will be easier when Native Assets feature finished.

I gueese you need to use arm64-v8a ABI if you want to install to your physical android device.

**Comment by IvRogoz** [comment]
I have a android x64 emulatior and have compiled with
conan build . -b missing -pr:h profiles/android-x86_64 -c tools.android:ndk_path="d:\@SDK\android-ndk-r26d"
Now I have libopencv_dart.so in \\build\\Android\\x86_64\\install
and have added 
{
  "dart.env": {
      "PATH": "${workspaceFolder}\\build\\Android\\x86_64\\install"
  }
}
to settings.json 
but now when I try to run example\main.dart nothing happens

**Comment by rainyl** [comment]
Take a look at setup script, https://github.com/rainyl/opencv_dart/blob/main/bin%2Fsetup_commands.dart#L93

**Comment by IvRogoz** [comment]
dart run opencv_dart:setup android --arch x86_64
Building package executable... 
Built opencv_dart:setup.
opencv_dart: working for android x86_64
Building with assumed project root in:
D:\Programing\Flutter\opencv_dart-main\
Using package:opencv_dart from D:\Programing\Flutter\opencv_dart-main\
Downloading prebuilt binary...
Downloading https://github.com/rainyl/opencv_dart/releases/download/v1.0.0+2/libopencv_dart-android-x86_64.tar.gz
Download Failed with status: 404

**Comment by rainyl** [comment]
This issue is not the problem of opencv_dart itself, I have no responsibility to answer your questions, and you guys even didn't star this project, closing.

If you have questions please open a new issue with Question template.
