### ISSUE TITLE
Regarding FloodFill

### ISSUE THREAD

**Issue by Marlenfranto** [rainyl/opencv_dart#235]
I have an OpenCV-based Android application that allows users to change the color of an image where they touch. We are currently exploring the possibility of migrating this functionality to Flutter, but I couldn't find the `floodFill` function in Flutter's OpenCV support. 

Is there any alternative method or approach to achieve similar functionality in Flutter?

 Below is the Android code for reference.

` for (int i = 0; i < points.size(); i++) {

            Point seedPoint = new Point(points.get(i).x * ((double) bitmap.getWidth() / (double) width), points.get(i).y * ((double) bitmap.getHeight() / (double) height));

            int floodFillFlag = 8;
            Imgproc.floodFill(mRgbMat, cannyMat, seedPoint, new Scalar((double) Color.red(mDefaultColor), (double) Color.green(mDefaultColor), (double) Color.blue(mDefaultColor)), new Rect(), new Scalar(5.0, 5.0, 5.0), new Scalar(5.0, 5.0, 5.0), floodFillFlag);
        }`

**Comment by rainyl** [comment]
Oh it's not implemented.

@Marlenfranto I can add it, do you need other unimplemented functions, so I can add them all.

**Comment by Marlenfranto** [comment]
@rainyl , at the moment, I specifically need the `floodFill` function, as all other image processing functions are working perfectly in my project. 

Thank you in advance for your assistance!

**Comment by rainyl** [comment]
@Marlenfranto Get it, I will add it later.

**Comment by rainyl** [comment]
I have added `cv.floodFill` and `cv.floodFillAsync`, check the example in test. https://github.com/rainyl/opencv_dart/blob/1167883aed2b425b6792bfd62ca9eea702e55493/test/imgproc/imgproc_test.dart#L288-L311

![image](https://github.com/user-attachments/assets/42e5c31d-dc1e-4334-bd44-b80a25ee23ba)

**Comment by rainyl** [comment]
@Marlenfranto BTW, this will be included in the next release, now you can update the dependency of opencv_dart to:

```yaml
  opencv_dart:
    git:
      url: https://github.com/rainyl/opencv_dart.git
      ref: 1167883
```

to use it for now.
