### ISSUE TITLE
Failed to lookup symbol 'FloodFill'

### ISSUE THREAD

**Issue by Marlenfranto** [rainyl/opencv_dart#238]
@rainyl , When I attempt to execute the `cv.floodFill` function, I encounter the following exception. 
Please see the details of the exception below:

`E/flutter ( 9850): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to lookup symbol 'FloodFill': undefined symbol: FloodFill

E/flutter ( 9850): #0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:33:70)
E/flutter ( 9850): #1      CvNativeImgproc._FloodFillPtr (package:opencv_dart/src/g/imgproc.g.dart:2362:38)
E/flutter ( 9850): #2      CvNativeImgproc._FloodFillPtr (package:opencv_dart/src/g/imgproc.g.dart)
E/flutter ( 9850): #3      CvNativeImgproc._FloodFill (package:opencv_dart/src/g/imgproc.g.dart:2363:27)
E/flutter ( 9850): #4      CvNativeImgproc._FloodFill (package:opencv_dart/src/g/imgproc.g.dart)
E/flutter ( 9850): #5      CvNativeImgproc.FloodFill (package:opencv_dart/src/g/imgproc.g.dart:2338:12)
E/flutter ( 9850): #6      floodFill.<anonymous closure> (package:opencv_dart/src/imgproc/imgproc.dart:334:20)
E/flutter ( 9850): #7      cvRun (package:opencv_dart/src/core/base.dart:83:76)
E/flutter ( 9850): #8      floodFill (package:opencv_dart/src/imgproc/imgproc.dart:333:3)
E/flutter ( 9850): #9      _MyAppState.rpPaintHSV (package:opencv_dart_example/main.dart:151:8)
E/flutter ( 9850): #10     _MyAppState.build.<anonymous closure>.<anonymous closure> (package:opencv_dart_example/main.dart:72:21)
E/flutter ( 9850): #11     State.setState (package:flutter/src/widgets/framework.dart:1203:30)
E/flutter ( 9850): #12     _MyAppState.build.<anonymous closure> (package:opencv_dart_example/main.dart:69:19)
E/flutter ( 9850): #13     TapGestureRecognizer.handleTapDown.<anonymous closure> (package:flutter/src/gestures/tap.dart:624:61)
E/flutter ( 9850): #14     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:344:24)
E/flutter ( 9850): #15     TapGestureRecognizer.handleTapDown (package:flutter/src/gestures/tap.dart:624:11)
E/flutter ( 9850): #16     BaseTapGestureRecognizer._checkDown (package:flutter/src/gestures/tap.dart:300:5)
E/flutter ( 9850): #17     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:277:7)
E/flutter ( 9850): #18     GestureArenaManager._resolveByDefault (package:flutter/src/gestures/arena.dart:269:25)
E/flutter ( 9850): #19     GestureArenaManager._tryToResolveArena.<anonymous closure> (package:flutter/src/gestures/arena.dart:249:31)
E/flutter ( 9850): #20     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter ( 9850): #21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)`

**Comment by rainyl** [comment]
v1.2.4 has been published, now please upgrade to v1.2.4 to use it, remember to run `flutter clean`

**Comment by rainyl** [comment]
Also, if you have any new problems, feel free to reopen this issue.
