### ISSUE TITLE
Exception has occurred.ArgumentError (Invalid argument(s): Failed to lookup symbol 'Image_IMRead': dlsym(RTLD_DEFAULT, Image_IMRead): symbol not found)

### ISSUE THREAD

**Issue by kitittat7j** [rainyl/opencv_dart#24]
**Describe the bug**
when I run the code on Simulator (17.4 version) and  Ios real device. I got those message Failed to lookup symbol 'Image_IMRead': dlsym(RTLD_DEFAULT, Image_IMRead): symbol not found) when i click to use the function cv.imread("some image") 

**To Reproduce**
1. Run simulator 
2. run opencv to read the image
3. See error

**Screenshots**
![Screenshot 2567-04-10 at 17 19 26](https://github.com/rainyl/opencv_dart/assets/166481576/776d8252-1329-4498-bb92-79654e284685)

opencv_dart : 1.0.0+1 
flutter version : 3.16.9

**Comment by kitittat7j** [comment]
I use flutter version : 3.16.9

**Comment by kitittat7j** [comment]
i also run dart run opencv_dart:setup ios -a arm64.It work fine.thank you

**Comment by rainyl** [comment]
You are welcome, if solved, please close this issue.
