### ISSUE TITLE
Live video feed processing

### ISSUE THREAD

**Issue by Marlenfranto** [rainyl/opencv_dart#241]
Is it possible to perform live video feed processing in OpenCV with Flutter? In Android, we have **CameraBridgeViewBase** to modify the live video feed. Is there a similar approach available for Flutter?

**Comment by rainyl** [comment]
Well, although opencv provides VideoCapture, which can open live video streams, I haven't tested it in Flutter, I recommend you to use media_kit, which is more widely used and offers Flutter widgets to work with videos. check more details at: https://github.com/media-kit/media-kit , Also, maybe this project can help you: https://github.com/xiaoyaocz/dart_simple_live

**Comment by rainyl** [comment]
I think this issue has been solved so I am going to close it, feel free to reopen it if anyone still have the same problem.
