### ISSUE TITLE
Failed to load dynamic library 'libopencv_dart.so': dlopen failed: library "libcamera2ndk.so" not found

### ISSUE THREAD

**Issue by ziyad-aljohani** [rainyl/opencv_dart#244]
**Describe the bug**
I get this exception when I run my code to decode Uint8List image.

E/flutter ( 2931): #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
E/flutter ( 2931): #2      loadNativeLibrary (package:opencv_dart/src/native_lib.dart:37:29)
E/flutter ( 2931): #3      cimgcodecs (package:opencv_dart/src/native_lib.dart:47:48)
E/flutter ( 2931): #4      cimgcodecs (package:opencv_dart/src/native_lib.dart)
E/flutter ( 2931): #5      imdecodeAsync.<anonymous closure> (package:opencv_dart/src/imgcodecs/imgcodecs_async.dart:91:32)
E/flutter ( 2931): #6      cvRunAsync (package:opencv_dart/src/core/base.dart:115:21)
E/flutter ( 2931): #7      imdecodeAsync (package:opencv_dart/src/imgcodecs/imgcodecs_async.dart:91:7)

**To Reproduce**
This is my code:
var res = await http.get(Uri.parse("https://avatars.githubusercontent.com/u/135967503?v=4"));
var buf = res.bodyBytes.buffer.asUint8List();
final im0 = await cv.imdecodeAsync(buf, cv.IMREAD_GRAYSCALE);

**Smartphone (please complete the following information):**
 - Android emulator
 -  API 23 - arm64 I think

Thank you for this great library. I'm so excited for the CV optical flow !

**Comment by rainyl** [comment]
use API 24 and above please.
