### ISSUE TITLE
Failed to lookup symbol 'Mat_New': dlsym(RTLD_DEFAULT, Mat_New): symbol not found

### ISSUE THREAD

**Issue by fpcxsun** [rainyl/opencv_dart#251]
**Describe the bug**
Failed to lookup symbol 'Mat_New': dlsym(RTLD_DEFAULT, Mat_New): symbol not found

**To Reproduce**
Flutter 3.22.3
opencv_dart 1.2.3 crash in iOS, work fine in Android

**Smartphone (please complete the following information):**
 - Device: iPhone 11,  iOS 17.6.1
 - ABI Version arm64-v8a

**Additional context**
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to lookup symbol 'Mat_New': dlsym(RTLD_DEFAULT, Mat_New): symbol not found
#0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:33:70)
#1      CvNativeCore._Mat_NewPtr (package:opencv_dart/src/g/core.g.dart:3016:80)
#2      CvNativeCore._Mat_NewPtr (package:opencv_dart/src/g/core.g.dart)
#3      CvNativeCore._Mat_New (package:opencv_dart/src/g/core.g.dart:3018:25)
#4      CvNativeCore._Mat_New (package:opencv_dart/src/g/core.g.dart)
#5      CvNativeCore.Mat_New (package:opencv_dart/src/g/core.g.dart:3010:12)
#6      new Mat.empty.<anonymous closure> (package:opencv_dart/src/core/mat.dart:116:23)
#7      cvRun (package:opencv_dart/src/core/base.dart:83:76)
#8      new Mat.empty (package:opencv_dart/src/core/mat.dart:116:5)
#9      imdecode (package:opencv_dart/src/imgcodecs/imgcodecs.dart:96:15)

**Comment by rainyl** [comment]
@fpcxsun refer to #200 , https://github.com/rainyl/opencv_dart/issues/200#issuecomment-2278057007

**Comment by fpcxsun** [comment]
I add it by myself，then it work.
<img width="640" alt="image" src="https://github.com/user-attachments/assets/96b918c0-8886-450c-9e9c-c1a4802d54b5">

**Comment by xiazhichao** [comment]
when create Mat object,Not work and I add it in embedded content,Is there a solution?
