### ISSUE TITLE
cv.imdecode giveing null data ,

### ISSUE THREAD

**Issue by KartikGavhale** [rainyl/opencv_dart#258]
**Describe the bug**
im trying to pick image from mobile galary , i used imdecodeasync to decode a 16MP resolution image , when i checked the returmed mat.data , its giveing me null

**To Reproduce**
1.using image picker to pick image from galary . 
2. select a image of 16MP resolution 
3. convert it to mat

**Comment by rainyl** [comment]
@KartikGavhale Thanks for your report.

Could you please attach an example image so I can test it?

**Comment by KartikGavhale** [comment]
Hi @rainyl  , i tried using two following code


      final data = File(imagepath).readAsBytesSync();
    Uint8List  bytes = data.buffer.asUint8List();
    colorimg = cv.imdecode(bytes,cv.IMREAD_ANYCOLOR);

and 
colorimg=cv.imread(imagepath);

both returned the empty data in mat without error 
I have to for the image picker to get 50% image quality then only its giveing me the data.

attaching referance image which i used
![20240928_172002 (1)](https://github.com/user-attachments/assets/67ec09d8-9cca-40b6-bc6d-883d34c6f1c9)

**Comment by rainyl** [comment]
@KartikGavhale Thanks for your response, but I cant reproduce it with the following steps:

- `flutter create -t app --platforms ios,android,windows,linux,macos --org dev.rainyl --project-name opencv_dart_issue258 opencv_dart_issue258`
- `cd opencv_dart_issue258`
- `flutter pub add image_picker opencv_dart`
- paste the following test code to `lib/main.dart`

<details>

```dart
// ignore_for_file: avoid_print

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:opencv_dart/opencv_dart.dart' as cv;
import 'package:image_picker/image_picker.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  var images = <Uint8List>[];

  @override
  void initState() {
    super.initState();
  }

  @override
  void dispose() {
    super.dispose();
  }

  Future<(cv.Mat, cv.Mat)> heavyTaskAsync(cv.Mat im, {int count=1000}) async {
    late cv.Mat gray, blur;
    for (var i = 0; i < count; i++) {
      gray = await cv.cvtColorAsync(im, cv.COLOR_BGR2GRAY);
      blur = await cv.gaussianBlurAsync(im, (7, 7), 2, sigmaY: 2);
    }
    return (gray, blur);
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Native Packages'),
        ),
        body: Container(
          alignment: Alignment.center,
          child: Column(
            children: [
              ElevatedButton(
                onPressed: () async {
                  final picker = ImagePicker();
                  final img = await picker.pickImage(source: ImageSource.gallery);
                  if (img != null) {
                    final path = img.path;
                    final mat = cv.imread(path);
                    print("cv.imread: width: ${mat.cols}, height: ${mat.rows}, path: $path");
                    debugPrint("mat.data.length: ${mat.data.length}");
                    // heavy computation
                    final (gray, blur) = await heavyTaskAsync(mat, count: 100);
                    setState(() {
                      images = [
                        cv.imencode(".png", mat).$2,
                        cv.imencode(".png", gray).$2,
                        cv.imencode(".png", blur).$2,
                      ];
                    });
                  }
                },
                child: const Text("Pick Image"),
              ),
              ElevatedButton(
                onPressed: () async {
                  final data = await DefaultAssetBundle.of(context).load("images/lenna.png");
                  final bytes = data.buffer.asUint8List();
                  // heavy computation
                  // final (gray, blur) = await heavyTask(bytes);
                  // setState(() {
                  //   images = [bytes, gray, blur];
                  // });
                  final (gray, blur) = await heavyTaskAsync(cv.imdecode(bytes, cv.IMREAD_COLOR));
                  setState(() {
                    images = [bytes, cv.imencode(".png", gray).$2, cv.imencode(".png", blur).$2];
                  });
                },
                child: const Text("Process"),
              ),
              Expanded(
                flex: 2,
                child: Row(
                  children: [
                    Expanded(
                      child: ListView.builder(
                        itemCount: images.length,
                        itemBuilder: (ctx, idx) => Card(
                          child: Image.memory(images[idx]),
                        ),
                      ),
                    ),
                    Expanded(
                      child: SingleChildScrollView(
                        child: Text(cv.getBuildInformation()),
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

```

</details>

- flutter run -d "windows"
- select the image you provided via `Pick Image` button

I also tested it on android and it worked fine.

![image](https://github.com/user-attachments/assets/0305e3b5-e6c6-4ab8-a3e9-02b30551c369)

![image](https://github.com/user-attachments/assets/a041512c-1491-420c-90e5-048dd521eef0)

**Comment by KartikGavhale** [comment]
@rainyl  can you confirm if you had picked image from gallery? Please test this with some good quality picture captured by camera  and choose it from gallery. I tried multiple time .

**Comment by rainyl** [comment]
@KartikGavhale Yes, it works in my test, even with large images (3472*4624)

![image](https://github.com/user-attachments/assets/4d8f7854-0ba9-41c4-b337-8441a010483a)

![opencv_dart_issue258](https://github.com/user-attachments/assets/a075cf60-d73c-48c1-ba9d-04ce7d826320)

**Comment by KartikGavhale** [comment]
@rainyl  , ok will try to get if i found any certain error. Thanks for the continues support buddy.
