### ISSUE TITLE
Invalid argument(s): Failed to lookup symbol 'Mat_New': dlsym(RTLD_DEFAULT, Mat_New): symbol not found

### ISSUE THREAD

**Issue by xiazhichao** [rainyl/opencv_dart#265]
Flutter 3.24.3
device: iphone
when create Mat object
error: Invalid argument(s): Failed to lookup symbol 'Mat_New': dlsym(RTLD_DEFAULT, Mat_New): symbol not found

**Comment by rainyl** [comment]
Refer to #212

Can't reproduce without more information, and you didn't follow the issue template, closed.
