### ISSUE TITLE
How to initialize the cv.Mat from Array2d

### ISSUE THREAD

**Issue by Nacriema** [rainyl/opencv_dart#266]
**Read README carefully first**
**Star :star: this project if you want to ask a question, no star, no answer**

## Question
Hi, currently I want to use the `cv.warpAffine(img, transformMatrix, (224, 224), ...)`. I have the transformMatrix as an `Array2d`, my question is to convert the `transformMatrix` from `Array2d` and then can pass it into the `cv.warpAffine` function. Can you give me the solution for my problem. Thank you in advance.

**Comment by rainyl** [comment]
@Nacriema refer to https://github.com/rainyl/opencv_dart/blob/d706f225ac8f785ebb96a2af93e66a9d48708f64/test/core/mat_test.dart#L912-L962

**Comment by rainyl** [comment]
If no more questions, I am going to close this issue, feel free to reopen it if you still have problems.

**Comment by Nacriema** [comment]
Thank you very much, this solved my problem.
