### ISSUE TITLE
Error: The plugin "opencv_dart" requires a higher minimum macOS deployment version than your application is targeting

### ISSUE THREAD

**Issue by ywu2014** [rainyl/opencv_dart#279]
**Describe the bug**
"opencv_dart" requires a higher minimum macOS deployment version；when i tried to resolve this problem, ld: library not found for -ld_classic occured

**To Reproduce**
1. create an empty flutter project
2. add opencv_dart: ^1.2.1 dependency
3. use `flutter run -d macos` to start the project

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/f795663f-2448-4b6f-bbdb-93f8556149a8)

**Desktop (please complete the following information):**
![image](https://github.com/user-attachments/assets/88c7a309-ad04-408b-add4-ad908bc0e863)

**Additional context**
i tried to change minimum macOS deployment version by modify platform :osx '10.14' in macos/Podfile to platform :osx '10.15' as below
![image](https://github.com/user-attachments/assets/52eb956e-5b2c-4fe4-a0f6-0fd7a306722b)
but another problem appear as show below
![image](https://github.com/user-attachments/assets/0e251c24-ac62-444c-abf0-f3e12d10cfe8)

**Comment by rainyl** [comment]
It seems that XCode 14.2 doesn't support the link option `-ld_classic`, which is used to supress warnings like `no platform load command found in ‘libxyz.a’, assuming: macOS`
- https://developer.apple.com/documentation/xcode-release-notes/xcode-15-release-notes#Linking
- https://wadetregaskis.com/no-platform-load-command-found-in-libxyz-a-assuming-macos/
- https://github.com/rainyl/dartcv/blob/9394c165f3404a696209eb316d3a3e49cb7a8526/DartCvMacOS.podspec#L46

I will remove it from `OTHER_LDFLAGS`

**Comment by ywu2014** [comment]
tks!

**Comment by rainyl** [comment]
@ywu2014 Update to 1.3.1 and try whether it works, `-ld_classic` will not be added with XCode < 15.0

**Comment by rainyl** [comment]
Well, kind of strange, looks like -ld_classic is still added.

Could you please run 
- `cd ~/.pub-cache/hosted/pub.dev/opencv_dart-1.3.1/macos`
- `pod lib lint --allow-warnings --verbose > a.log`

and attach `a.log` so I can analyze it?

**Comment by rainyl** [comment]
Okay, reproduced, will working on it.

**Comment by ywu2014** [comment]
> Well, kind of strange, looks like -ld_classic is still added.
> 
> Could you please run
> 
> * `cd ~/.pub-cache/hosted/pub.dev/opencv_dart-1.3.1/macos`
> * `pod lib lint --allow-warnings --verbose > a.log`
> 
> and attach `a.log` so I can analyze it?

OK.
In my system, dir ~/.pub-cache/hosted/pub.dev is empty, as shown below
<img width="717" alt="image" src="https://github.com/user-attachments/assets/ab7b64f4-3cbc-4676-a46a-6eab8d4c5712">

so i route to pub.flutter-io.cn dir, and there is opencv_dart-1.3.1
<img width="1350" alt="image" src="https://github.com/user-attachments/assets/eebba467-bf3b-4408-9151-4de9cf7c1959">

[a.log](https://github.com/user-attachments/files/17595075/a.log)

**Comment by rainyl** [comment]
@ywu2014 Fine.

it's because the expressions in podspec uploaded to Cocoapods will be evaluated and saved as constants in json, I have totally remove the link flag, try to use:

```yaml
opencv_dart:
  git:
    url: https://github.com/rainyl/opencv_dart.git
    ref: ebc1dc172854812e02c925c74eba195e335ae49b
    path: packages/opencv_dart/
```

**Comment by ywu2014** [comment]
> @ywu2014 Fine.
> 
> it's because the expressions in podspec uploaded to Cocoapods will be evaluated and saved as constants in json, I have totally remove the link flag, try to use:
> 
> ```yaml
> opencv_dart:
>   git:
>     url: https://github.com/rainyl/opencv_dart.git
>     ref: ebc1dc172854812e02c925c74eba195e335ae49b
>     path: packages/opencv_dart/
> ```

i have tried, but this time shows iOS deployment version problem
![image](https://github.com/user-attachments/assets/c363649c-537e-46bd-9353-a35575a9af39)

and i just create project support MacOS only, this is my project create command `flutter create demo3 --platforms=macos`，and form vscode left side view，there's no iOS related files or dir

**Comment by rainyl** [comment]
It's strange, since DartCvMacOS only supports osx, 10.15 https://github.com/rainyl/dartcv/blob/13b077fd98475ff49aff50400f7a8f34aae62b95/DartCvMacOS.podspec#L30

I tested it using:
- `flutter create --template=app --platforms=macos demo`
- edit pubspec.yaml and add the above dep
- edit `macos/Podfile` and change the minimum version to 10.15
- `flutter run -d "macos"`

and it works, so try to remove the project and create a fresh one. You can also run `pod cache clean --all` to delete the cache.

**Comment by ywu2014** [comment]
i followed your steps，and below is the result in my system

<img width="1436" alt="image" src="https://github.com/user-attachments/assets/0b5db9b0-d4ff-49e1-acb4-5ab2ef0da822">

![image](https://github.com/user-attachments/assets/d805e6a0-1265-4572-b3fd-617627a24765)

![image](https://github.com/user-attachments/assets/17a5f974-481d-49b6-8e5c-576c913186ee)

**Comment by rainyl** [comment]
@ywu2014 try to remove the cache of cocoapods, `rm -rf ~/.cocoapods/repos/trunk`

**Comment by ywu2014** [comment]
> @ywu2014 try to remove the cache of cocoapods, `rm -rf ~/.cocoapods/repos/trunk`

the same problem, nothing changed
<img width="1226" alt="image" src="https://github.com/user-attachments/assets/0c428321-e22e-4a6c-a509-e1a21e899a0d">

even if i run
1. pod cache clean --all
2. rm -rf ~/.cocoapods/repos/trunk
3. create another empyt project flutter create --template=app --platforms=macos demo5
the same problem still apears

**Comment by ywu2014** [comment]
OK, tks！

**Comment by ywu2014** [comment]
i just upgrade my cocoapods version from 1.15.2 to 1.16.2 right now, and it works! thanks!

**Comment by rainyl** [comment]
> i just upgrade my cocoapods version from 1.15.2 to 1.16.2 right now, and it works! thanks!

Glad it works! have fun :)
