### ISSUE TITLE
Failed to load dynamic library 'libopencv_dart.so': dlopen failed: library "libopencv_dart.so" not found. 

### ISSUE THREAD

**Issue by fangjunai** [rainyl/opencv_dart#29]
Error: 
ArgumentError (Invalid argument(s): Failed to load dynamic library 'libopencv_dart.so': dlopen failed: library "libopencv_dart.so" not found)

Win10 x64, Android7(qemu),

Flutter 3.19.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision bae5e49bc2 (9 weeks ago) • 2024-02-13 17:46:18 -0800
Engine • revision 04817c99c9
Tools • Dart 3.3.0 • DevTools 2.31.1

Where is libopencv_dart.so stored in?

**Comment by rainyl** [comment]
Read README carefully.
https://github.com/rainyl/opencv_dart?tab=readme-ov-file#important

**Comment by VishGoria** [comment]
@rainyl the readme is ambiguous. kindly clarify the most required steps to run the sample app as I'm also getting the same error while I've already tried to run the following commands:

dart run opencv_dart:setup android --arch armeabi-v7a
dart run opencv_dart:setup android --arch arm64-v8a

**Comment by rainyl** [comment]
@VishGoria Allright, I have added more detailes in [README](https://github.com/rainyl/opencv_dart/blob/main/README.md) and [example](https://github.com/rainyl/opencv_dart/blob/main/example/README.md)

Releated issues:

- https://github.com/rainyl/opencv_dart/issues/24
- https://github.com/rainyl/opencv_dart/issues/23
- https://github.com/rainyl/opencv_dart/issues/12

**Comment by VishGoria** [comment]
@rainyl The commands are only creating empty folders inside the opencv_dart\android\src\main\jniLibs 
although the libraries are added in the opencv_dart\.caches folder and I've also tried to manually copy the .tar.gz from .caches to the corresponding arch folder in android/jniLibs but still getting the same error. Urgent help required
thanks in advance

**Comment by rainyl** [comment]
@VishGoria paste your command output please, you can also manually extract .tar.gz and copy libopencv_dart.so to corresponding directory

**Comment by rainyl** [comment]
> @rainyl The commands are only creating empty folders inside the opencv_dart\android\src\main\jniLibs although the libraries are added in the opencv_dart.caches folder and I've also tried to manually copy the .tar.gz from .caches to the corresponding arch folder in android/jniLibs but still getting the same error. Urgent help required thanks in advance

Apologize for my mistake, It is a bug, will be fixed quickly.

**Comment by gustavovisentini** [comment]
Launching lib/main.dart on iPhone 15 Pro in debug mode...
Running Xcode build...                                                  
 └─Compiling, linking and signing...                        994ms
Xcode build done.                                            3,7s
Failed to build iOS app
Error (Xcode): Framework 'opencv_dart' not found


Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)


Could not build the application for the simulator.
Error launching application on iPhone 15 Pro.

A follow the instructions README, but not works,
Macbook air M1

**Comment by rainyl** [comment]
I have no mac M1 so can't test, I suggest you to add -v option to see the logs or setup it manually with -f option and try again.

This package supports universal framewrok but only tested on x86_64 simulators by myself, I don't know whether it works on arm64 simulators.

**Comment by gustavovisentini** [comment]
Using -v for me and setting Enable **flutter config --enable-native-assets** but everytime that run, shows the same result



➜  dropx flutter config --enable-native-assets
Setting "enable-native-assets" value to "true".

You may need to restart any open editors for them to read new settings.
➜  dropx flutter run -v                       
[   +3 ms] executing: sw_vers -productName
[  +11 ms] Exit code 0 from: sw_vers -productName
[        ] macOS
[        ] executing: sw_vers -productVersion
[   +8 ms] Exit code 0 from: sw_vers -productVersion
[        ] 14.0
[        ] executing: sw_vers -buildVersion
[  +10 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 23A344
[        ] executing: uname -m
[   +3 ms] Exit code 0 from: uname -m
[        ] arm64
[   +3 ms] executing: sysctl hw.optional.arm64
[   +3 ms] Exit code 0 from: sysctl hw.optional.arm64
[        ] hw.optional.arm64: 1
[  +60 ms] executing: sysctl hw.optional.arm64
[   +7 ms] Exit code 0 from: sysctl hw.optional.arm64
[        ] hw.optional.arm64: 1
[        ] executing: /usr/bin/arch -arm64e xcrun xcodebuild -version
[ +104 ms] Exit code 0 from: /usr/bin/arch -arm64e xcrun xcodebuild -version
[        ] Xcode 15.4
           Build version 15F31d
[   +1 ms] executing: /usr/bin/arch -arm64e xcrun xcdevice list --timeout 5
[   +3 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'LegacyCanvasKitRemover' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +19 ms] executing: /Users/gustavovisentini/Library/Android/sdk/platform-tools/adb devices -l
[        ] executing: /usr/bin/arch -arm64e xcrun xcdevice list --timeout 2
[        ] /usr/bin/arch -arm64e xcrun simctl list devices booted iOS --json
[        ] executing: /usr/bin/arch -arm64e xcrun simctl list devices booted iOS --json
[   +1 ms] executing: /usr/bin/arch -arm64e xcrun simctl list devices booted
[  +76 ms] Exit code 0 from: /usr/bin/arch -arm64e xcrun simctl list devices booted
[        ] == Devices ==
           -- iOS 17.5 --
               iPhone 15 Pro (B88196B5-220A-4EFF-B167-D36273068532) (Booted)
[  +26 ms] List of devices attached
[  +66 ms] {
             "devices" : {
               "com.apple.CoreSimulator.SimRuntime.iOS-17-5" : [
                 {
                   "lastBootedAt" : "2024-06-26T14:07:03Z",
                   "dataPath" : "\/Users\/gustavovisentini\/Library\/Developer\/CoreSimulator\/Devices\/B88196B5-220A-4EFF-B167-D36273068532\/data",
                   "dataPathSize" : 1321336832,
                   "logPath" : "\/Users\/gustavovisentini\/Library\/Logs\/CoreSimulator\/B88196B5-220A-4EFF-B167-D36273068532",
                   "udid" : "B88196B5-220A-4EFF-B167-D36273068532",
                   "isAvailable" : true,
                   "logPathSize" : 565248,
                   "deviceTypeIdentifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-15-Pro",
                   "state" : "Booted",
                   "name" : "iPhone 15 Pro"
                 }
               ]
             }
           }
[+2698 ms] [
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "17.5 (21F79)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad16,4",
                        "identifier" : "0DB5D748-8101-4CFA-8A07-FE53ADC4BF32",
                        "architecture" : "arm64",
                        "modelUTI" : "com.apple.ipad-pro-m4-1",
                        "modelName" : "iPad Pro 11-inch (M4)",
                        "name" : "iPad Pro 11-inch (M4)",
                        "ignored" : false
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "17.5 (21F79)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone15,4",
                        "identifier" : "6C010D3B-1587-4AF3-9522-D52950C3EE12",
                        "architecture" : "arm64",
                        "modelUTI" : "com.apple.iphone-15-1",
                        "modelName" : "iPhone 15",
                        "name" : "iPhone 15",
                        "ignored" : false
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "17.5 (21F79)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad14,9",
                        "identifier" : "5740B4B7-04C7-4ACE-865E-2DFA0B018423",
                        "architecture" : "arm64",
                        "modelUTI" : "com.apple.ipad-air-m2-1",
                        "modelName" : "iPad Air 11-inch (M2)",
                        "name" : "iPad Air 11-inch (M2)",
                        "ignored" : false
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "17.5 (21F79)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad14,11",
                        "identifier" : "F7B8412F-C327-46B5-AA29-5AB1096852B0",
                        "architecture" : "arm64",
                        "modelUTI" : "com.apple.ipad-air-m2-13-1",
                        "modelName" : "iPad Air 13-inch (M2)",
                        "name" : "iPad Air 13-inch (M2)",
                        "ignored" : false
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "17.5 (21F79)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone16,2",
                        "identifier" : "B6BE2EA6-0E70-425D-A05B-6C399BA82043",
                        "architecture" : "arm64",
                        "modelUTI" : "com.apple.iphone-15-pro-max-1",
                        "modelName" : "iPhone 15 Pro Max",
                        "name" : "iPhone 15 Pro Max",
                        "ignored" : false
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "17.5 (21F79)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone16,1",
                        "identifier" : "B88196B5-220A-4EFF-B167-D36273068532",
                        "architecture" : "arm64",
                        "modelUTI" : "com.apple.iphone-15-pro-1",
                        "modelName" : "iPhone 15 Pro",
                        "name" : "iPhone 15 Pro",
                        "ignored" : false
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "17.5 (21F79)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad16,6",
                        "identifier" : "CAAF8FFC-4B61-467B-B115-98691763158B",
                        "architecture" : "arm64",
                        "modelUTI" : "com.apple.ipad-pro-m4-13-1",
                        "modelName" : "iPad Pro 13-inch (M4)",
                        "name" : "iPad Pro 13-inch (M4)",
                        "ignored" : false
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "17.5 (21F79)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone15,5",
                        "identifier" : "64C67F0C-F6D6-4BE1-A798-2506EEE4C672",
                        "architecture" : "arm64",
                        "modelUTI" : "com.apple.iphone-15-plus-1",
                        "modelName" : "iPhone 15 Plus",
                        "name" : "iPhone 15 Plus",
                        "ignored" : false
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "17.5 (21F79)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad14,1",
                        "identifier" : "475FDAE1-7317-4B6C-956E-643144A3794E",
                        "architecture" : "arm64",
                        "modelUTI" : "com.apple.ipad-mini6-1",
                        "modelName" : "iPad mini (6th generation)",
                        "name" : "iPad mini (6th generation)",
                        "ignored" : false
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "17.5 (21F79)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPad13,18",
                        "identifier" : "5B53FE52-2ED1-4F26-8C67-CAC5970EDE34",
                        "architecture" : "arm64",
                        "modelUTI" : "com.apple.ipad-10-1",
                        "modelName" : "iPad (10th generation)",
                        "name" : "iPad (10th generation)",
                        "ignored" : false
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "17.5 (21F79)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone14,6",
                        "identifier" : "100672A0-77C4-4D12-AC10-EBFDCEAFD206",
                        "architecture" : "arm64",
                        "modelUTI" : "com.apple.iphone-se3-1",
                        "modelName" : "iPhone SE (3rd generation)",
                        "name" : "iPhone SE (3rd generation)",
                        "ignored" : false
                      },
                      {
                        "ignored" : false,
                        "modelCode" : "MacBookAir10,1",
                        "simulator" : false,
                        "modelName" : "MacBook Air",
                        "operatingSystemVersion" : "14.0 (23A344)",
                        "identifier" : "00008103-000A348A2133001E",
                        "platform" : "com.apple.platform.macosx",
                        "architecture" : "arm64e",
                        "interface" : "usb",
                        "available" : true,
                        "name" : "My Mac",
                        "modelUTI" : "com.apple.macbookair-late-2020"
                      }
                    ]
[   +1 ms] executing: /usr/bin/arch -arm64e xcrun devicectl --version
[  +63 ms] Exit code 0 from: /usr/bin/arch -arm64e xcrun devicectl --version
[        ] 355.28
[   +1 ms] executing: /usr/bin/arch -arm64e xcrun devicectl list devices --timeout 5 --json-output
/var/folders/0x/brqx8sgj01l3bf23q_70k1080000gn/T/flutter_tools.c6C4PE/core_devices.rqVerF/core_device_list.json
[+1063 ms] No devices found.
[        ] {
             "info" : {
               "arguments" : [
                 "devicectl",
                 "list",
                 "devices",
                 "--timeout",
                 "5",
                 "--json-output",
                 "/var/folders/0x/brqx8sgj01l3bf23q_70k1080000gn/T/flutter_tools.c6C4PE/core_devices.rqVerF/core_device_list.json"
               ],
               "commandType" : "devicectl.list.devices",
               "environment" : {
                 "TERM" : "xterm-256color"
               },
               "jsonVersion" : 2,
               "outcome" : "success",
               "version" : "355.28"
             },
             "result" : {
               "devices" : [

               ]
             }
           }

[   +6 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +52 ms] Skipping pub get: version match.
[  +74 ms] Generating /Users/gustavovisentini/Documents/GitHub/dropx/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +63 ms] "flutter run" took 4.364ms.
[   +5 ms] Package(s) opencv_dart require the native assets feature to be enabled. Enable using `flutter config --enable-native-assets`.
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      nativeBuildRequired (package:flutter_tools/src/isolated/native_assets/native_assets.dart:255:5)
           <asynchronous suspension>
           #2      dryRunNativeAssetsIOS (package:flutter_tools/src/isolated/native_assets/ios/native_assets.dart:26:8)
           <asynchronous suspension>
           #3      dryRunNativeAssets (package:flutter_tools/src/isolated/native_assets/native_assets.dart:376:26)
           <asynchronous suspension>
           #4      HotRunner.run (package:flutter_tools/src/run_hot.dart:375:26)
           <asynchronous suspension>
           #5      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:833:27)
           <asynchronous suspension>
           #6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #8      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
           <asynchronous suspension>
           #12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #14     main (package:flutter_tools/executable.dart:93:3)
           <asynchronous suspension>
           
           
[ +201 ms] ensureAnalyticsSent: 200ms
[        ] Running 1 shutdown hook
[        ] Shutdown hooks complete
[  +10 ms] exiting with code 1
