### ISSUE TITLE
Face Recognition is possible?

### ISSUE THREAD

**Issue by ZiyadgodilDev** [rainyl/opencv_dart#292]
## Question
@rainyl @abdelaziz-mahdy @Jiinwoo @einsitang  Can I implement face recognition using opencv_dart plugin?

## Objective
We aim to develop an attendance application using face recognition technology to ensure accuracy and prevent fraudulent check-ins and check-outs. The key priority is to achieve high accuracy in face recognition while incorporating face liveness detection to differentiate between real faces and photo images.

**Comment by abdelaziz-mahdy** [comment]
For detecting faces yes you can do it and matching 

Here and example where it groups images based on their faces similarity https://github.com/abdelaziz-mahdy/face_grouping

But sadly I don't know about the liveness
