### ISSUE TITLE
[Android] Support 16KB Page Size

### ISSUE THREAD

**Issue by mhdjazmati** [rainyl/opencv_dart#294]
**Describe the bug**

`    final img = await cv.imreadAsync(imagePath, flags: cv.IMREAD_GRAYSCALE);`

when it goes here it will crash with exception:

Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libdartcv.so': dlopen failed: empty/missing DT_HASH/DT_GNU_HASH in "/data/app/~~6THc7nmbhNWQ1qGf0VwAkQ==/com.example.opencv_oc-Rn_I_jOHmr7ZXoEHurFG1Q==/base.apk!/lib/arm64-v8a/libdartcv.so" (new hash type from the future?)

keep in mind this is my arm64-v8a folder:
**libavcodec.so	
libavformat.so		
libswresample.so
libavfilter.so		
libavutil.so		
libswscale.so**

also when i try to run the command:
_dart run opencv_dart:setup android -a arm64-v8a -f_
i got error : Could not find `bin/setup.dart` in package `opencv_dart`.

keep in mind on MacOS platform it is working

**To Reproduce**
just make new project add lib to pubspec, run with the example code.

**Desktop (please complete the following information):**
 - OS: android

**Smartphone (please complete the following information):**
 - Device: emulator
 - ABI Version  arm64-v8a

**Comment by rainyl** [comment]
@mhdjazmati I can't reproduce it with Android API level 34, are you using Android 35?

> also when i try to run the command:
> dart run opencv_dart:setup android -a arm64-v8a -f
> i got error : Could not find bin/setup.dart in package opencv_dart.

Since v1.3.0, the setup commands have been deprecated, because the `libdartcv` will be build locally.

Also, it would be helpful if you can attach the compiled `libdartcv.so`, you can find it in `build/app/intermediates/stripped_native_libs/debug/out/lib/arm64-v8a`

Related:
- https://github.com/android/ndk/issues/1866

**Comment by mhdjazmati** [comment]
```
android {
    namespace = "com.example.opencv_oc"
    compileSdk = flutter.compileSdkVersion
    ndkVersion "25.1.8937393"

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = 17
    }

    defaultConfig {
        minSdk = 26
        targetSdk = 34
        versionCode = flutter.versionCode
        versionName = flutter.versionName
        applicationId = "com.example.opencv_oc"
    }

    buildTypes {
        release {
            signingConfig = signingConfigs.debug
        }
    }
}
```

<img width="531" alt="Screenshot 2024-11-21 at 1 15 07 PM" src="https://github.com/user-attachments/assets/8eaf457e-c542-43e4-acfc-e4dc25c2744a">

this is the size of it for it and i attached it as zip
[Uploading libdartcv.so.zip…]()

**Comment by mhdjazmati** [comment]
also my emulator api is 35

**Comment by mhdjazmati** [comment]
<img width="374" alt="Screenshot 2024-11-21 at 1 28 35 PM" src="https://github.com/user-attachments/assets/225667dd-c872-417e-9a93-46c2158fa2cf">
is this the issue ? the emulator?

**Comment by rainyl** [comment]
> is this the issue ? the emulator?

Very likely, there are many similiar issues about 16KB page size:
- https://github.com/opencv/opencv/issues/26027
- https://github.com/realm/realm-java/issues/7894

**Comment by rainyl** [comment]
I have reproduced the bug using API 35 with 16KB page size, will look into and try to fix it.

For now, please use emulators without `16KB Page Size`
