### ISSUE TITLE
how to copy a ROI in a image

### ISSUE THREAD

**Issue by eramirez3** [rainyl/opencv_dart#301]
I am using openCV in javascript to extract a ROI from the center of the image

let roiArea = dst_frame.roi(new cv.Rect(newTopLeftX, topLeftY, width, height)); 

how to do it using openCV_dart

thank you!!

David

**Comment by rainyl** [comment]
@eramirez3 Please refer to
- #151 
- #267 
and try whether it works for you, let me know if not.

**Comment by eramirez3** [comment]
HI, I implement this, but I am not sure if this is the best approximation for better speed processing ?

```
   cv.Mat extractROI(cv.Mat img, int startX, int startY, int width, int height) {
    // Ensure the ROI is within the image boundaries
      if (startX < 0 || startY < 0 || startX + width > img.cols || startY + height > img.rows) {
        throw Exception("ROI is out of image bounds.");
      }

      // Extract rows and columns based on the ROI
      cv.Mat roiRows = img.rowRange(startY, startY + height);
      cv.Mat roiImage = roiRows.colRange(startX, startX + width);

      // Return the extracted ROI
      return roiImage;
    }
```

**Comment by rainyl** [comment]
You can use `Mat.region` directy. 
- https://pub.dev/documentation/dartcv4/latest/dartcv.core/Mat/region.html
- https://docs.opencv.org/4.x/d3/d63/classcv_1_1Mat.html#aa7ec97373406215f2d4bc72cc1d27036

**Comment by eramirez3** [comment]
thanks that solve my question
