### ISSUE TITLE
有一个比较严重的问题，使用HoughCircles寻找图片中的圆，找不到圆会一直卡死状态

### ISSUE THREAD

**Issue by Robotboy36** [rainyl/opencv_dart#303]
static houghCircles(
    cv.Mat mat, {
    double dp = 1,
    double minDist = 1000,
    double param1 = 100,
    double param2 = 100,
    int minRadius = 100,
    int maxRadius = 0,
  }) {
    return cv.HoughCircles(mat, cv.HOUGH_GRADIENT, dp, minDist, param1: param1, param2: param2, minRadius: minRadius, maxRadius: maxRadius);
  }

cv.Mat circlesMat = houghCircles(image, maxRadius: image.width ~/ 2);

**Comment by abdelaziz-mahdy** [comment]
if possible explain the problem and give us an example with the problem so we can figure out the problem

**Comment by rainyl** [comment]
1. 虽然我能理解你在说什么但为了给遇到相同问题的人以参考，建议使用英文。Although I know what you are talking about, using English is recommended to provide solutions for others with the same problem.
2. Questioning manners, as abdelaziz-mahdy said, please provide a reproducible example to help us locating the real problem. At leaset, do NOT ignore the issue template, the required items are essential to solve the problem.
3. I cant reproduce it.

Closed, if you still have any problems, open new issues with correct format.
