### ISSUE TITLE
file_picker package compatibility issue on texture_renderer example

### ISSUE THREAD

**Issue by fadelfffar** [rainyl/opencv_dart#306]
![Screenshot from 2024-12-12 04-55-55](https://github.com/user-attachments/assets/06bac315-e54f-46c2-a489-a7e2e58d6bc4)
Help please, I can't seem to run the texture_renderer example cause of uncompatibility with the file_picker packgage, I was trying all different file_picker version from 8.1.2 until 8.1.5 

> /home/fadel/.pub-cache/hosted/pub.dev/file_picker-8.1.5/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java:257: error: cannot find symbol
        if (registrar != null) {
            ^
  symbol:   variable registrar
  location: class FilePickerPlugin
/home/fadel/.pub-cache/hosted/pub.dev/file_picker-8.1.5/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java:260: error: cannot find symbol
            registrar.addActivityResultListener(this.delegate);
            ^
  symbol:   variable registrar
  location: class FilePickerPlugin
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':file_picker:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

_Originally posted by @fadelfffar in https://github.com/rainyl/opencv_dart/discussions/33#discussioncomment-11538059_

**Comment by rainyl** [comment]
@fadelfffar I can't reproduce it with Ubuntu 24.04.

```console
➜  texture_renderer git:(main) ✗ flutter build linux --release
Resolving dependencies... (1.0s)
Downloading packages...
+ async 2.11.0 (2.12.0 available)
+ boolean_selector 2.1.1 (2.1.2 available)
+ characters 1.3.0 (1.4.0 available)
+ clock 1.1.1 (1.1.2 available)
+ collection 1.18.0 (1.19.1 available)
+ cross_file 0.3.4+2
+ cupertino_icons 1.0.8
+ dartcv4 1.0.1
+ fake_async 1.3.1 (1.3.2 available)
+ ffi 2.1.3
+ file_picker 8.1.5
+ flutter 0.0.0 from sdk flutter
+ flutter_lints 2.0.3 (5.0.0 available)
+ flutter_plugin_android_lifecycle 2.0.23
+ flutter_test 0.0.0 from sdk flutter
+ flutter_web_plugins 0.0.0 from sdk flutter
+ leak_tracker 10.0.5 (10.0.8 available)
+ leak_tracker_flutter_testing 3.0.5 (3.0.9 available)
+ leak_tracker_testing 3.0.1
+ lints 2.1.1 (5.1.0 available)
+ logging 1.3.0
+ matcher 0.12.16+1 (0.12.17 available)
+ material_color_utilities 0.11.1 (0.12.0 available)
+ meta 1.15.0 (1.16.0 available)
+ opencv_dart 1.3.3
+ path 1.9.0 (1.9.1 available)
+ plugin_platform_interface 2.1.8
+ sky_engine 0.0.99 from sdk flutter
+ source_span 1.10.0 (1.10.1 available)
+ stack_trace 1.11.1 (1.12.0 available)
+ stream_channel 2.1.2
+ string_scanner 1.2.0 (1.4.0 available)
+ term_glyph 1.2.1
+ test_api 0.7.2 (0.7.4 available)
+ texture_rgba_renderer 0.0.16
+ vector_math 2.1.4
+ vm_service 14.2.5 (15.0.0 available)
+ web 1.1.0
+ win32 5.9.0
Changed 39 dependencies!
19 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.

Building Linux application...
✓ Built build/linux/x64/release/bundle/texture_rgba_renderer_example
➜  texture_renderer git:(main) ✗ screenfetch
                          ./+o+-       
                  yyyyy- -yyyyyy+      OS: Ubuntu 24.04 noble
               ://+//////-yyyyyyo      Kernel: x86_64 Linux 6.8.0-49-generic
           .++ .:/++++++/-.+sss/`      Uptime: 1d 16h 28m
         .:++o:  /++++++++/:--:/-      Packages: 1900
        o:+o+:++.`..```.-/oo+++++/     Shell: zsh 5.9
       .:+o:+o/.          `+sssoo+/    Disk: 2.6T / 5.2T (51%)
  .++/+:+oo+o:`             /sssooo.   CPU: AMD Ryzen 9 9950X 16-Core @ 32x 7.835GHz
 /+++//+:`oo+o               /::--:.   GPU: 
 \+/+o+++`o++o               ++////.   RAM: 64605MiB / 126404MiB
  .++.o+++oo+:`             /dddhhh.
       .+.o+oo:.          `oddhhhh+
        \+.++o+o``-````.:ohdhhhhh+
         `:o+++ `ohhhhhhhhyo++os:
           .o:`.syhhhhhhh/.oo++o`
               /osyyyyyyo++ooo+++/
                   ````` +oo+++o\:
                          `oo++.
➜  texture_renderer git:(main) ✗
```

Also, It seems not a problem of opencv_dart, why do you open the issue here rather than file_picker.

P.S., You do not need to use both opencv_dart and opencv_core, just choose one of them, depending on whether you need videoio module.

**Comment by fadelfffar** [comment]
Sorry my bad for posting this as issues, on another note I forgot to mention that using Imageformat as in imencode(cv.Imageformat.png.cv, img, params) is not working on another example (i forgot which)

**Comment by rainyl** [comment]
`cv.Imageformat` was deprecated a long time ago, you can use ".png" directly. `cv.imencode(".png", image)`

**Comment by rainyl** [comment]
abdelaziz-mahdy has reported this in file_picker, check this:
- https://github.com/miguelpruivo/flutter_file_picker/issues/1643

**Comment by fadelfffar** [comment]
okidoki thanks for your help, I'm gonna close this issue

**Comment by fadelfffar** [comment]
![Screenshot from 2024-12-12 17-15-45](https://github.com/user-attachments/assets/1f5ba407-1c88-41cc-8cec-516a7e12c880)
Hello, I have use the temporary fix from abdelaziz-mahdy, but get a GNUC_PREFEQ compiler error and a arm64-v8a error from dart cv, any idea why? thanks in advance ;)

**Comment by rainyl** [comment]
I think you can just use 8.1.4, it works fine for me.

**Comment by fadelfffar** [comment]
hmmm weird, I already tried that earlier. Does this need Nvidia gpu in anyway?

**Comment by rainyl** [comment]
> hmmm weird, I already tried that earlier. Does this need Nvidia gpu in anyway?

Nope. Did you use the exact version of 8.1.4? https://github.com/miguelpruivo/flutter_file_picker/issues/1643#issuecomment-2537812174

Also mind that texture_rgba_renderer only supports windows, linux and macos for now, android is not supported.

**Comment by fadelfffar** [comment]
yes i ded, without the ^ on pubspec.yaml, maybe because I run it on android lol, thanks

**Comment by rainyl** [comment]
All right, kind of weird...
