### ISSUE TITLE
Cannot run macOS app because of ffmpeg version mismatch 

### ISSUE THREAD

**Issue by azlekov** [rainyl/opencv_dart#31]
**Describe the bug**
Recently homebrew updates my `ffmpeg` to version 7, while it looks like the project is searching for version 6

**To Reproduce**
1. Have a working project
2. Execute `brew update` which will update ffmpeg
3. Try running the app
4. See error:

```
dyld[58652]: Library not loaded: /opt/homebrew/opt/ffmpeg/lib/libavcodec.60.dylib
  Referenced from: <292CC2EA-6E11-35F9-B2DF-1DF95AE7FE94> /Users/azlekov/Workspace/biokom-flow/build/macos/Build/Products/Debug/Biokom Flow.app/Contents/Frameworks/libopencv_dart.dylib
  Reason: tried: '/opt/homebrew/opt/ffmpeg/lib/libavcodec.60.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/ffmpeg/lib/libavcodec.60.dylib' (no such file), '/opt/homebrew/opt/ffmpeg/lib/libavcodec.60.dylib' (no such file)
```

**Expected behavior**
It should work as before

**Desktop (please complete the following information):**
 - OS: macOS 14.4.1

**Additional context**
I tried:

```
brew uninstall ffmpeg
brew install ffmpeg@6
flutter clean
flutter run
```

Still without success. Looks like the lib is located into `/opt/homebrew/opt/ffmpeg@6/` instead of `/opt/homebrew/opt/ffmpeg/`

**Comment by azlekov** [comment]
Workaround:

```
ln -s /opt/homebrew/opt/ffmpeg@6 /opt/homebrew/opt/ffmpeg
```

**Comment by rainyl** [comment]
Yes, this package was compiled with ffmpeg@6, after you install ffmpeg@6 with brew, it will tell you to link, you can use `brew link --overwrite ffmpeg@6` to link it

**Comment by rainyl** [comment]
Wait, I double checked CI of Macos, It seems ffmpeg is not correctly configured, I am working on it.
https://github.com/rainyl/opencv.full/actions/runs/8722998969/job/23930165038

**Comment by azlekov** [comment]
> Yes, this package was compiled with ffmpeg@6, after you install ffmpeg@6 with brew, it will tell you to link, you can use `brew link --overwrite ffmpeg@6` to link it

I already tried, but unfortunately seems not to be working:

```
brew unlink ffmpeg@6 && brew link --force ffmpeg@6
Unlinking /opt/homebrew/Cellar/ffmpeg@6/6.1.1... 111 symlinks removed.
Linking /opt/homebrew/Cellar/ffmpeg@6/6.1.1... 111 symlinks created.
```

**Comment by rainyl** [comment]
Which version? I tested the example with v1.0.1 and it worked. Could you please paste the full log?

**Comment by azlekov** [comment]
Yes, with v1.0.1 is working fine! Thanks! What was the issue?

**Comment by rainyl** [comment]
You are welcome, if no further problems please close this issue.

**Comment by azlekov** [comment]
Tested on another machine, where I have faced same issue. Not seems to be resolved! Thanks again!
