### ISSUE TITLE
gaussianBlurAsync error when using kSize values other than (7, 7)

### ISSUE THREAD

**Issue by Correct-Syntax** [rainyl/opencv_dart#310]
**Describe the bug**

Using values other than (7, 7) for the ``kSize`` in the ``gaussianBlurAsync`` method results in a crash.

**To Reproduce**
1. Use the code from https://github.com/rainyl/opencv_dart/blob/main/packages/opencv_core/example/lib/main.dart as your project.
2. Change ``blur = await cv.gaussianBlurAsync(im, (7, 7), 2, sigmaY: 2);`` to ``blur = await cv.gaussianBlurAsync(im, (8, 8), 2, sigmaY: 2);``
3. When you select an image with the "Pick Image" button, it results in an error/crash.

If I set the kSize back to (7, 7) it works, but any other value doesn't.

**Expected behavior**
The blur method should not crash with values other than  (7, 7).

**Screenshots**

**Desktop:**
 - OS: Windows 10

**Additional context**

The error:
```
Exception has occurred.
CvException (CvException(code: -215, msg:OpenCV(4.10.0) D:\a\opencv.full\opencv.full\opencv\modules\imgproc\src\smooth.dispatch.cpp:294: error: (-215:Assertion failed) ksize.width > 0 && ksize.width % 2 == 1 && ksize.height > 0 && ksize.height % 2 == 1 in function 'cv::createGaussianKernels'
) in cv::createGaussianKernels of file D:\a\opencv.full\opencv.full\opencv\modules\imgproc\src\smooth.dispatch.cpp:294)
```

Maybe this is related to https://github.com/rainyl/opencv_dart/issues/180?

**Comment by rainyl** [comment]
@Correct-Syntax Have you tried other odd values like (9, 9), (11, 9), (15, 15)? Please note that the kernel size of gaussianBlur must be ODD, refer to https://docs.opencv.org/4.x/d4/d86/group__imgproc__filter.html#gae8bdcd9154ed5ca3cbc1766d960f45c1

**Comment by Correct-Syntax** [comment]
@rainyl Ah, I see. I'm used to the Python version of OpenCV where they must silently correct the values, not matter what is specified.
