### ISSUE TITLE
Yesterday I could run my application, but today I can't run my application anymore because 'Framework opencv_dart not found'.

### ISSUE THREAD

**Issue by IzraelAA** [rainyl/opencv_dart#47]
Launching lib/main.dart on iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: ----
Running Xcode build...
Xcode build done.                                           33.6s
Failed to build iOS app
Could not build the precompiled application for the device.
Error (Xcode): Framework 'opencv_dart' not found

Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)

Error launching application on iPhone.

**Comment by rainyl** [comment]
provide the following information please:

1.  have you tried to clean and rerun?
2. which version?
3. have you run setup?
4. the output of setup.

**Comment by IzraelAA** [comment]
This error show when i try to run app 
For the flutter pub get i have no issue

1. Yes ,i do.
2. Flutter version
Flutter (Channel stable, 3.19.2, on macOS 14.4 23E214 darwin-arm64, locale en-ID)
Xcode version
Xcode 15.1.
3. Yes ,i do.
4. Output of setup
Launching lib/main.dart on iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: ----
Running Xcode build...
Xcode build done. 33.6s
Failed to build iOS app
Could not build the precompiled application for the device.
Error (Xcode): Framework 'opencv_dart' not found

Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)

Error launching application on iPhone.

**Comment by rainyl** [comment]
2. Which version of opencv_dart?

3,4. Setup means `dart run opencv_dart:setup`

**Comment by IzraelAA** [comment]
ohhh i see,i skip this part thanks.
