### ISSUE TITLE
Can you give me example for stitching

### ISSUE THREAD

**Issue by IzraelAA** [rainyl/opencv_dart#48]
**Read README carefully first**
**Star :star: this project if you want to ask a question, no star, no answer**

## Question
Describe the question here
// Function to create a panorama from images using OpenCV
img.Image createPanorama(List<img.Image> images) {
  // Convert images to OpenCV Mat vectors
  final cv.VecMat vecMat =
      cv.VecMat.fromList(images.map((image) => matFromImage(image)).toList());

  // Create Stitcher object
  final cv.Stitcher stitcher = cv.Stitcher.create();

  // Estimate transformations and stitch images
  final cv.StitcherStatus status = stitcher.estimateTransform(vecMat);
  if (status != cv.StitcherStatus.OK) {
    throw Exception('Failed to estimate transformations for stitching');
  }

  final (cv.StitcherStatus, cv.Mat) stitchResult = stitcher.composePanorama();
  if (stitchResult.$1 != cv.StitcherStatus.OK) {
    throw Exception('Failed to stitch images');
  }

  // Convert stitched image to image format from the image package
  final Uint8List imageData = stitchResult.$2.data;
  final img.Image panoramaImage = img.decodeImage(imageData)!;

  return panoramaImage;
}

cv.Mat matFromImage(img.Image image) {
  final cv.Mat mat = cv.Mat.fromList(
      image.height, image.width, cv.MatType.CV_8UC3, image.getBytes());
  return mat;
}

this is my code for stitching but when i try to stitching i always failed

**Comment by rainyl** [comment]
Confirmed, it's a bug, I will release a hotfix version soon.

**Comment by rainyl** [comment]
@IzraelAA I have published v1.0.3+1, could you please update to v1.0.3+1 and test it?

You can refer to https://github.com/rainyl/opencv_dart/blob/8813680d8044474fd142af030d258112c5d5891a/test/stitching_test.dart#L61-L81 for more usage.

Feel free to reopen this issue if the problem still exists.

**Comment by rainyl** [comment]
As the exception says, the image may be empty, check your input image first by mat.isEmpty, if the opencv images are not empty, please provide a minimal example to reproduce.

I also noticed that you are converting img.Image to mat, make sure the convention is success.

**Comment by IzraelAA** [comment]
**MY CODE**


  // Fungsi untuk membuat panorama dari gambar-gambar menggunakan OpenCV
  img.Image createPanorama(List<img.Image> images) {
    List<cv.Mat> listMat = [];
    imageList.forEach((element) {
      listMat.add(cv.imread(element.path, flags: cv.IMREAD_COLOR));
    });
    // Ubah gambar-gambar menjadi vektor OpenCV Mat
    final cv.VecMat vecMat = cv.VecMat.fromList(listMat);

    print(vecMat.length);
    // Buat objek Stitcher
    final cv.Stitcher stitcher = cv.Stitcher.create();

    // Perkiraan transformasi dan jahit gambar-gambar
    final cv.StitcherStatus status = stitcher.estimateTransform(vecMat);
    print('status: $status');
    if (status != cv.StitcherStatus.OK) {
      print('Gagal memperkirakan transformasi untuk stitching');
    }

    final (cv.StitcherStatus, cv.Mat) stitchResult = stitcher.composePanorama(
      images: vecMat,
    );
    print('stitchResult: $stitchResult');
    if (stitchResult.$1 != cv.StitcherStatus.OK) {
      print('Gagal menjahit gambar-gambar');
    }

    // Konversi gambar jahitan ke format image dari package image
    final Uint8List imageData = stitchResult.$2.data;
    final img.Image panoramaImage = img.decodeImage(imageData)!;

    return panoramaImage;
  }
  
  
  **RESULT**
  
  Performing hot reload...
Syncing files to device iPhone...
Reloaded 116 of 3745 libraries in 729ms (compile: 348 ms, reload: 124 ms, reassemble: 135 ms).
flutter: 10
flutter: status: StitcherStatus.OK
flutter: Error: CvException(code: ErrorCode(-215), err: , msg:OpenCV(4.9.0) /Users/runner/work/opencv.full/opencv.full/build/opencv/modules/stitching/src/stitcher.cpp:139: error: (-215:Assertion failed) imgs.size() == imgs_.size() in function 'composePanorama'
) in composePanorama of file /Users/runner/work/opencv.full/opencv.full/build/opencv/modules/stitching/src/stitcher.cpp:139

I have already modified it, but I still get the different error.

**Comment by rainyl** [comment]
I think this is the problem of input data, the opencv_dart looks worked fine, I don't know what's in `vecMat`, maybe you can try to google the exception.
