### ISSUE TITLE
Segmentation Fault When Calling meanStdDev or Mat.variance()

### ISSUE THREAD

**Issue by VishGoria** [rainyl/opencv_dart#59]
**Describe the bug**
I am encountering a segmentation fault when calling meanStdDev or the laplac.variance()  in the opencv_dart package. The crash seems to occur specifically after calculating the Laplacian of a grayscale image. This issue started happening after updating to the latest version of the package.

**Environment**
Package Version: 1.0.3+2
Flutter Version: 3.19.1
Platform: Android
Device: Redmi
Device Architecture: arm64-v8a
Android Version: 14

**To Reproduce**

1. Load an image from a file.
2. Convert the image to grayscale.
3. Calculate the Laplacian of the grayscale image.
4. Call **meanStdDev** on the Laplacian matrix.

**Code Snippet**
`import 'dart:io';
import 'dart:typed_data';
import 'package:opencv_dart/opencv_dart.dart' as cv;
import 'package:flutter/foundation.dart';

Future<void> detectBlur(File file) async {
  try {
    // Load image from file
    final Uint8List imageData = await file.readAsBytes();
    debugPrint('Image data loaded successfully.');

    // Convert image data to OpenCV format
    final src = cv.imdecode(imageData, cv.IMREAD_COLOR);
    if (src.isEmpty) {
      debugPrint('Failed to decode image.');
      return;
    }
    debugPrint('Image decoded successfully.');

    // Convert image to grayscale
    final gray = cv.cvtColor(src, cv.COLOR_BGR2GRAY);
    if (gray.isEmpty) {
      debugPrint('Failed to convert image to grayscale.');
      return;
    }
    debugPrint('Image converted to grayscale.');

    // Calculate Laplacian variance as a measure of blur
    final laplac = cv.laplacian(gray, cv.MatType.CV_64F);
    if (laplac.isEmpty) {
      debugPrint('Failed to calculate Laplacian.');
      return;
    }
    debugPrint('Laplacian calculated.');

    // Ensure meanStdDev is being called correctly
    final meanStdDevResult = cv.meanStdDev(laplac);
    final mean = meanStdDevResult.$1;
    final stddev = meanStdDevResult.$2;

    debugPrint('Mean: ${mean.val}, StdDev: ${stddev.val}');

    // Calculate the variance using the new variance method
    final variance = stddev.val[0] * stddev.val[0];

    // Determine if the image is blurry based on the variance threshold
    const threshold = 400.0; // Adjust as needed
    final isBlurry = variance < threshold;
    debugPrint('Variance: $variance');
    debugPrint('Image is blurry: $isBlurry');

    // Clean up
    src.release();
    gray.release();
    laplac.release();
  } catch (e) {
    debugPrint('Error occurred: $e');
  }
}
`
**Error Logs**
`I/flutter (25538): Laplacian calculated.
I/libc    (25538): handling signal: 11
F/libc    (25538): Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x13 in tid 25696 (1.ui), pid 25538 (cv_dart_example)
...
`

**Expected behavior**
The meanStdDev function should execute without causing a segmentation fault.
The function should return the mean and standard deviation of the Laplacian matrix as expected.
The application should be able to proceed to calculate the variance and determine if the image is blurry based on the variance threshold.

**Additional context**
The issue seems to be a null pointer dereference within the native library. The code works until the meanStdDev call. Here are the relevant changes from the changelog that might be related:

API change in v1.0.2: (Mat mean, Mat stdDev) meanStdDev(InputArray src, {OutputArray? mean, OutputArray? stdDev}) => (Scalar mean, Scalar stddev) meanStdDev(InputArray src, {InputArray? mask})
New: Mat.stdDev(), Mat.variance()
New: Scalar operator +, -, *, /, sqrt(), pow(int n)

The following existing code works fine on 1.0.1

` // Load image from assets or other sources
      final imageData = await file.readAsBytes();
      print('Image data loaded successfully.');

      // Convert image data to OpenCV format
      final src = cv.imdecode(imageData, cv.IMREAD_COLOR);
      print('Image decoded successfully.');

      // Convert image to grayscale
      final gray = cv.cvtColor(src, cv.COLOR_BGR2GRAY);
      print('Image converted to grayscale.');

      // Calculate Laplacian variance as a measure of blur
      final laplac = cv.laplacian(gray, cv.MatType.CV_64F);
      print('Laplacian calculated.');

      // Get the mean and standard deviation directly
      final meanStdDevResult = cv.meanStdDev(laplac);
      final mean = meanStdDevResult.$1;
      final stddev = meanStdDevResult.$2;

      // Calculate the variance
      variance = stddev.at<double>(0, 0) * stddev.at<double>(0, 0);`

**Comment by rainyl** [comment]
Have you rerun setup command `dart run opencv_dart:setup` after upgrading?

**Comment by rainyl** [comment]
I will test and try to reproduce it, thanks

**Comment by rainyl** [comment]
I have tested your code with some small changes and it worked fine, both on windows and android...

<details>

<summary>Code</summary>

```dart
import 'package:opencv_dart/opencv_dart.dart' as cv;

void func() {
  // Convert image data to OpenCV format
  final src = cv.imread("test/images/circles.jpg", flags: cv.IMREAD_COLOR);
  if (src.isEmpty) {
    print('Failed to decode image.');
    return;
  }
  print('Image decoded successfully.');

  // Convert image to grayscale
  final gray = cv.cvtColor(src, cv.COLOR_BGR2GRAY);
  if (gray.isEmpty) {
    print('Failed to convert image to grayscale.');
    return;
  }
  print('Image converted to grayscale.');

  // Calculate Laplacian variance as a measure of blur
  final laplac = cv.laplacian(gray, cv.MatType.CV_64F);
  if (laplac.isEmpty) {
    print('Failed to calculate Laplacian.');
    return;
  }
  print('Laplacian calculated.');

  // Ensure meanStdDev is being called correctly
  final (mean, stddev) = cv.meanStdDev(laplac);
  final sd = laplac.stdDev();
  assert(sd == stddev);
  print('Mean: ${mean.val}, StdDev: ${stddev.val}');

  // Calculate the variance using the new variance method
  final variance = laplac.variance().val1;

  // Determine if the image is blurry based on the variance threshold
  const threshold = 400.0; // Adjust as needed
  final isBlurry = variance < threshold;
  print('Variance: $variance');
  print('Image is blurry: $isBlurry');
}

void main(List<String> args) {
  for (var i = 0; i < 1000; i++) {
    func();
  }
}
```

</details>

I also checked the source code carefully, but it seems every thing is ok, so the only reason I can think of is that the previous step may failed, try to save gray and laplac to see if it is really success

**Comment by VishGoria** [comment]
@rainyl Thank you for your prompt response.

After running the following setup commands:
`dart run opencv_dart:setup android --arch x86_64
dart run opencv_dart:setup android --arch armeabi-v7a
dart run opencv_dart:setup android --arch arm64-v8a
`
and updating the code to reference the variance correctly:

`variance = laplac.variance().val1;
`
the issue has been resolved.

I appreciate your assistance!

**Comment by rainyl** [comment]
You are welcome.
