### ISSUE TITLE
How to "getPerspectiveTransform" and "warpPerspective"?

### ISSUE THREAD

**Issue by tekink** [rainyl/opencv_dart#61]
## Question
I want to warp a picture by taken camera. I detect rectangle but i can't find corners of rectangle. 

```
  Future<Uint8List> heavyTask(Uint8List buffer) async {
    final ret = Isolate.run(() {
      final im = cv.imdecode(Uint8List.fromList(buffer), cv.IMREAD_COLOR);
      late cv.Mat gray, blur,canny,contour;
      cv.VecVecPoint point;
      gray = cv.cvtColor(im, cv.COLOR_BGR2GRAY);
      blur = cv.gaussianBlur(im, (5, 5), 1, sigmaY: 2);
      canny = cv.canny(blur, 0, 50);
      (point, contour) = cv.findContours(canny, cv.RETR_EXTERNAL, cv.CHAIN_APPROX_NONE);
      int maxval = 0;
      cv.VecPoint max = point.first;
      for (var element in point) {
        if (element.length > maxval) {
          maxval = element.length;
          max = element;
        }
      }

      cv.Mat draw = cv.drawContours(im, point, -1, cv.Scalar.blue);
      cv.Mat tra = cv.getPerspectiveTransform(
          max,
          cv.VecPoint.fromList([
            cv.Point(0, 0),
            cv.Point(0, 100),
            cv.Point(100, 0),
            cv.Point(100, 100),
          ]));
      return cv.imencode(cv.ImageFormat.png.ext, draw);
    });
    return ret;
  }
```
It can detect rectangle and draw contour
![Screenshot_1716215973](https://github.com/rainyl/opencv_dart/assets/88088517/a4ba8e3c-44b3-4d47-9913-27ec0e1d7f70)

I got error at cv.getPerspectiveTransform 

> Reloaded 1 of 797 libraries in 685ms (compile: 17 ms, reload: 168 ms, reassemble: 257 ms).
> D/EGL_emulation( 7180): app_time_stats: avg=2339.90ms min=6.37ms max=55623.45ms count=24
> D/EGL_emulation( 7180): app_time_stats: avg=1311.41ms min=1311.41ms max=1311.41ms count=1
> E/cv::error()( 7180): OpenCV(4.9.0) Error: Assertion failed (src.checkVector(2, CV_32F) == 4 && dst.checkVector(2, CV_32F) == 4) in getPerspectiveTransform, file /home/runner/work/opencv.full/opencv.full/build/opencv/modules/imgproc/src/imgwarp.cpp, line 3547
> E/flutter ( 7180): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: CvException(code: ErrorCode(-215), err: , msg:OpenCV(4.9.0) /home/runner/work/opencv.full/opencv.full/build/opencv/modules/imgproc/src/imgwarp.cpp:3547: error: (-215:Assertion failed) src.checkVector(2, CV_32F) == 4 && dst.checkVector(2, CV_32F) == 4 in function 'getPerspectiveTransform'
> E/flutter ( 7180): ) in getPerspectiveTransform of file /home/runner/work/opencv.full/opencv.full/build/opencv/modules/imgproc/src/imgwarp.cpp:3547
> E/flutter ( 7180): #0      cvRun (package:opencv_dart/src/core/base.dart:69:5)
> E/flutter ( 7180): #1      getPerspectiveTransform.<anonymous closure> (package:opencv_dart/src/imgproc/imgproc.dart:1261:5)
> E/flutter ( 7180): #2      cvRunArena (package:opencv_dart/src/core/base.dart:84:31)
> E/flutter ( 7180): #3      getPerspectiveTransform (package:opencv_dart/src/imgproc/imgproc.dart:1259:10)
> E/flutter ( 7180): #4      _MyAppState.heavyTask.<anonymous closure> (package:demo/main.dart:54:23)
> E/flutter ( 7180): #5      _RemoteRunner._run (dart:isolate:1090:47)
> E/flutter ( 7180): #6      _RemoteRunner._remoteExecute (dart:isolate:1084:12)
> E/flutter ( 7180): #7      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300:17)
> E/flutter ( 7180): #8      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
> E/flutter ( 7180):

**Comment by rainyl** [comment]
check the length of max

**Comment by thanhle7** [comment]
> ## Question
> 
> I want to warp a picture by taken camera. I detect rectangle but i can't find corners of rectangle.
> 
> ```
>   Future<Uint8List> heavyTask(Uint8List buffer) async {
>     final ret = Isolate.run(() {
>       final im = cv.imdecode(Uint8List.fromList(buffer), cv.IMREAD_COLOR);
>       late cv.Mat gray, blur,canny,contour;
>       cv.VecVecPoint point;
>       gray = cv.cvtColor(im, cv.COLOR_BGR2GRAY);
>       blur = cv.gaussianBlur(im, (5, 5), 1, sigmaY: 2);
>       canny = cv.canny(blur, 0, 50);
>       (point, contour) = cv.findContours(canny, cv.RETR_EXTERNAL, cv.CHAIN_APPROX_NONE);
>       int maxval = 0;
>       cv.VecPoint max = point.first;
>       for (var element in point) {
>         if (element.length > maxval) {
>           maxval = element.length;
>           max = element;
>         }
>       }
> 
>       cv.Mat draw = cv.drawContours(im, point, -1, cv.Scalar.blue);
>       cv.Mat tra = cv.getPerspectiveTransform(
>           max,
>           cv.VecPoint.fromList([
>             cv.Point(0, 0),
>             cv.Point(0, 100),
>             cv.Point(100, 0),
>             cv.Point(100, 100),
>           ]));
>       return cv.imencode(cv.ImageFormat.png.ext, draw);
>     });
>     return ret;
>   }
> ```
> 
> It can detect rectangle and draw contour ![Screenshot_1716215973](https://private-user-images.githubusercontent.com/88088517/332100837-a4ba8e3c-44b3-4d47-9913-27ec0e1d7f70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNTc2MzQsIm5iZiI6MTcxNjI1NzMzNCwicGF0aCI6Ii84ODA4ODUxNy8zMzIxMDA4MzctYTRiYThlM2MtNDRiMy00ZDQ3LTk5MTMtMjdlYzBlMWQ3ZjcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDAyMDg1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5NzY5OTEyOWM2ZDk5MTVmMWVmOGE5MjczNWNiNmNjYzU3MDIxOTM0NDY4ODcwZGFiMjI2MTVkZTUyODNmMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._5L5S1dbPjhOS3Q-vQmtjqHCkK5d4B_HvpgZe-SIoN8)
> 
> I got error at cv.getPerspectiveTransform
> 
> > Reloaded 1 of 797 libraries in 685ms (compile: 17 ms, reload: 168 ms, reassemble: 257 ms).
> > D/EGL_emulation( 7180): app_time_stats: avg=2339.90ms min=6.37ms max=55623.45ms count=24
> > D/EGL_emulation( 7180): app_time_stats: avg=1311.41ms min=1311.41ms max=1311.41ms count=1
> > E/cv::error()( 7180): OpenCV(4.9.0) Error: Assertion failed (src.checkVector(2, CV_32F) == 4 && dst.checkVector(2, CV_32F) == 4) in getPerspectiveTransform, file /home/runner/work/opencv.full/opencv.full/build/opencv/modules/imgproc/src/imgwarp.cpp, line 3547
> > E/flutter ( 7180): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: CvException(code: ErrorCode(-215), err: , msg:OpenCV(4.9.0) /home/runner/work/opencv.full/opencv.full/build/opencv/modules/imgproc/src/imgwarp.cpp:3547: error: (-215:Assertion failed) src.checkVector(2, CV_32F) == 4 && dst.checkVector(2, CV_32F) == 4 in function 'getPerspectiveTransform'
> > E/flutter ( 7180): ) in getPerspectiveTransform of file /home/runner/work/opencv.full/opencv.full/build/opencv/modules/imgproc/src/imgwarp.cpp:3547
> > E/flutter ( 7180): #0      cvRun (package:opencv_dart/src/core/base.dart:69:5)
> > E/flutter ( 7180): #1      getPerspectiveTransform. (package:opencv_dart/src/imgproc/imgproc.dart:1261:5)
> > E/flutter ( 7180): #2      cvRunArena (package:opencv_dart/src/core/base.dart:84:31)
> > E/flutter ( 7180): #3      getPerspectiveTransform (package:opencv_dart/src/imgproc/imgproc.dart:1259:10)
> > E/flutter ( 7180): #4      _MyAppState.heavyTask. (package:demo/main.dart:54:23)
> > E/flutter ( 7180): #5      _RemoteRunner._run (dart:isolate:1090:47)
> > E/flutter ( 7180): #6      _RemoteRunner._remoteExecute (dart:isolate:1084:12)
> > E/flutter ( 7180): #7      _delayEntrypointInvocation. (dart:isolate-patch/isolate_patch.dart:300:17)
> > E/flutter ( 7180): #8      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
> > E/flutter ( 7180):

I addressed the same problem by using bookmarks :)

**Comment by thanhle7** [comment]
> check the length of max

Thank you for your wonderful work!

**Comment by rainyl** [comment]
https://docs.opencv.org/4.x/da/d54/group__imgproc__transform.html#ga20f62aa3235d869c9956436c870893ae

According to the documentation of opencv, the src and dst must be 4-points, that's why it complains `Assertion failed (src.checkVector(2, CV_32F) == 4 && dst.checkVector(2, CV_32F) == 4) in getPerspectiveTransform`, I tested your code and the `max` is not a 4-point Vector, so please check your algorithm.

Closed.

**Comment by gustavovisentini** [comment]
its possible order by size this vector VecVecPoint? 
My code in c++

`std::vector<int> pointsVector;
    for(int i=0;i<contours.size();i++){
        pointsVector.push_back(contourArea(contours[i]));
    }
    //std::cout<<"\n Vetor Ordenado:\n\n";
    std::sort(pointsVector.begin(), pointsVector.end());
    for(int i=0;i<pointsVector.size();i++){
        //std::cout<<"\n"<<pointsVector[i];
    }
    
    int areaTotalGotas=0;
    for(int i=0;i<pointsVector.size();i++){
        areaTotalGotas=areaTotalGotas+pointsVector[i];
    }
    
    //std::cout<<"\nVolume: "<<areaTotalGotas<<"\n\n";
    int dmvPre = areaTotalGotas/2;
    int dmvAux=0;
    int dmv=0;
    int pos=0;
    for(int i=0;i<=pointsVector.size();i++){
        if (dmvAux<dmvPre){
            dmvAux=dmvAux+pointsVector[i];
            pos = i;
        }
    }
    dmv = pointsVector[pos];
    //std::cout<<"\n\nDMV "<<dmv<<"\n\n Volume medio calculado: "<<dmvPre<<"\n\n";`

**Comment by rainyl** [comment]
@gustavovisentini please open new issues for new questions.
