### ISSUE TITLE
Memory consumption 

### ISSUE THREAD

**Issue by abdelaziz-mahdy** [rainyl/opencv_dart#64]
**Describe the bug**
memory is not being freed correctly i think
this is my example https://github.com/abdelaziz-mahdy/face_grouping 

try to pick a dir with images in it it should extract the faces in it, 

from the devtools the memory should be 100mb 
<img width="1499" alt="image" src="https://github.com/rainyl/opencv_dart/assets/25157308/e3bdf762-fc79-4c1e-9a65-96642779687a">

but in activity monitor its 2 gb
<img width="764" alt="image" src="https://github.com/rainyl/opencv_dart/assets/25157308/247fb0b2-f1f2-4d77-a209-b777945b37dd">

**Expected behavior**
i think the memory should be the same as devtools and since they are not the same i think there is a problem with how the c part frees the memory 

**Desktop (please complete the following information):**
 - OS: Macbook pro m2

**Smartphone (please complete the following information):**
 - Device: Macos
 - ABI Version arm64

**Additional context**

**Comment by rainyl** [comment]
I have tested your example, yes, on windows a memory leak also observed.

It seems native resources are not correctly freed in cv.imread and cv.imencode, could you please replace the dependency of opencv_dart with `issue-64` branch in your pubspec.yaml and test it? I tested on windows and it seems ok.

**Comment by rainyl** [comment]
It seems an increase of ~20M still exists every time opening a directory, but much better now, and the reason may be an abuse of arena, but I am not clear why...

Anyway, I will reassess all arena recently.

**Comment by abdelaziz-mahdy** [comment]
i can confirm its much better now 
<img width="787" alt="image" src="https://github.com/rainyl/opencv_dart/assets/25157308/2f37ba87-41b3-41cd-9d6c-241649d093ed">
its lower in devtools, dont know if ffi objects are not kept in the tracking or something 
<img width="562" alt="image" src="https://github.com/rainyl/opencv_dart/assets/25157308/b2e4f691-1b7f-49e2-a91e-f2ea68e4b34d">

**Comment by rainyl** [comment]
Just for remind myself,

According to https://github.com/dart-lang/sdk/issues/54233 , dart objects are small but native objects are large, so GC will not execute as we expected to free native resources timely, but I am still confusing why arena will not release memory automactically...

Releated:
- https://github.com/dart-lang/sdk/issues/54233
- https://github.com/dart-lang/native/issues/848

**Comment by rainyl** [comment]
- [x] reassess the use of Arena
- [ ] Add [bool attach=true] to all native struct wrappers
- [ ] Add explicit free methods to free native resources manaully, maybe called `release()`, `free()` or `dispose()`

**Comment by abdelaziz-mahdy** [comment]
<img width="739" alt="image" src="https://github.com/rainyl/opencv_dart/assets/25157308/70f06563-71ca-4252-b39e-34ec92770c5b">
 in some cases i still face the same problem, yes it got reduced alot but still happens, do you know how can i identify objects in memory so i can dispose what is not disposed, or we can check it to check why GC doesnt clean it
 
 btw i opened devtools and forced GC but it didnt delete the objects

**Comment by rainyl** [comment]
Yes, the memory increases constantly even when I switch around different tabs... will keep tracking
