### ISSUE TITLE
Remove setup script, download libs when building

### ISSUE THREAD

**Issue by rainyl** [rainyl/opencv_dart#65]
**Is your feature request related to a problem? Please describe.**

> since native assets are experimental, and i do find that the setup command hard to use for most developers, dont you think we should make the cmake download the libs when launching or compiling the app? if you dont mind i can work on it, and leave this pr if other people request it

> For windows and linux it is reasonable, but android, ios and macos doesn't use cmake, I am wondering how to make flutter download the libs automatically? writing separate download scripts for gradlea and pod?

> for android yes gradle
> in general we can check this https://github.com/media-kit/media-kit/tree/main/libs in media_kit libs get downloaded on app build

> Making sense, I will open a new issue to track it, but I am not familiar with macos and ios development, if you are interest in it, PRs are welcome!

https://github.com/rainyl/opencv_dart/pull/63#issuecomment-2135038827

**Comment by abdelaziz-mahdy** [comment]
Just a question, would you like the libs each to be their own lib? Like media_kit or in the same package ?

**Comment by rainyl** [comment]
I prefer a universal one, so please just keep the current structure. 😄

**Comment by rainyl** [comment]
@abdelaziz-mahdy #66 has been merged, I am going to close this issue, thanks for your contributions~ 😄
