### ISSUE TITLE
mat show in statefullwidget

### ISSUE THREAD

**Issue by asanghehe** [rainyl/opencv_dart#7]
please explain how to show Mat image in flutter widget Pages

**Comment by rainyl** [comment]
TL;DR, use cv.imencode() to get a encoded Uint8List and then use Image.memory()

Take a look at [example](https://github.com/rainyl/opencv_dart/blob/main/example/lib/main.dart)

BTW, if you still use [dart image library](https://pub.dev/packages/image), you probably can also try to get Mat.data and construct a img.Image, note that Mat.data contains pixel values and have no headers for an image, so DO NOT pass Mat.data to Image.memory() directly!

**Comment by asanghehe** [comment]
Thank you. I have checked the method and it shows that I have successfully displayed it, but I can only use the thread (flutter compute() method) to use opencv_dart, otherwise it will get stuck. Anyway, I can use it

**Comment by rainyl** [comment]
Asynchronous calls are not supported yet, so heavy computations should not be done in the main thread, you may need to use isolate, compute() also spawns a new thread.
