### ISSUE TITLE
Framework 'opencv_dart' not found

### ISSUE THREAD

**Issue by arozdorozhniuk** [rainyl/opencv_dart#75]
## Question
I'm getting this error trying to launch ios. I've tried launching example inside opencv_dart and it works almost fine. At least it launches. What can be the cause of this error?

```
Failed to build iOS app
Error (Xcode): Framework 'opencv_dart' not found
Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)
```

P.S. It is probably because i'm trying to use your plugin inside of another plugin, and definitely doing something wrong.

**Comment by rainyl** [comment]
Using opencv_dart inside another plugin has not been tested, please provide an minimal example to reproduce it.

**Comment by arozdorozhniuk** [comment]
> Using opencv_dart inside another plugin has not been tested, please provide a minimal example to reproduce it.

I've basically created a plugin wih this command:
`flutter create --template=plugin --platforms=android,ios some_plugin`
And added your plugin as a dependency in main pubspec.yaml like that:
```
dependencies:
  flutter:
    sdk: flutter
  opencv_dart: ^1.0.5
  plugin_platform_interface: ^2.0.2
  ```
  
  I can provide full package but literally done nothing else with it.

**Comment by rainyl** [comment]
get it. may i ask you that you run on a simulator or real device ?

**Comment by rainyl** [comment]
@arozdorozhniuk 
Confirmed, You can run setup command manually to solve this, refer to README for detailed setup commands.

It's because the incorrect working directory in Makefile of ios, I am considering to compile locally instead of download from releases, please setup manually until it is finished.

**Comment by arozdorozhniuk** [comment]
I've tried calling `dart run opencv_dart:setup ios --arch x64` or `arm64 ` for simulator or device accordingly. But it seems that it does nothing.
Should I refer to some other setup process in readme?

**Comment by rainyl** [comment]
> /Users/arozdorozhniuk/.pub-cache/hosted/pub.dev/opencv_dart-1.0.5/ios

please take a look at `/Users/arozdorozhniuk/.pub-cache/hosted/pub.dev/opencv_dart-1.0.5/ios` and see whether `opencv_dart.framework` is there and ensure the content of `opencv_dart.framework` is not empty, you can manually delete it and try to re-run the setup commands.

**Comment by rainyl** [comment]
Try to delete the directory and re-run setup, and run the example to see whether it works

**Comment by arozdorozhniuk** [comment]
I've tried all of that, and it seems like opencv_dart exists but somehow it is not being found.

Also, i've just reilsed that 1.0.4 version is working and it is becoming even stranger now

**Comment by rainyl** [comment]
All right, please downgrade to v1.0.4 for now and waiting for #78 to be finished.

**Comment by arozdorozhniuk** [comment]
Thanks a lot, you're really helpful!

**Comment by rainyl** [comment]
You are welcome.

It almost finished, could you please test whether it works for you with the following deps:
```yaml
opencv_dart:
    git:
      url: https://github.com/rainyl/opencv_dart
      ref: 96a936a
```

Please install the dependencies before running examples if you haven't install them, especially conan:
```bash
brew install --force --overwrite ninja ffmpeg@6 conan
brew link --overwrite ffmpeg@6
conan profile detect -f
```

**Comment by arozdorozhniuk** [comment]
It works now!

**Comment by rainyl** [comment]
[v1.0.5+1](https://pub.dev/packages/opencv_dart/versions/1.0.5+1) has been published, I have tested it on macos (x86_64) and ios simulator (x86_64), but not tested on arm64 although the workflow passed, if you are using arm64 devices please test it, if it doesn't work please open a new issue. :)
