### ISSUE TITLE
Auto setup from remote

### ISSUE THREAD

**Issue by rainyl** [rainyl/opencv_dart#76]
**Is your feature request related to a problem? Please describe.**

Current auto setup will still download libs from releases, using setup commands, but the command needs correct working directory, i.e., user project directory, and now the parent directory is the cached package directory of opencv_dart, which is not correct, BUT I didn't find any approaches to get user project directory, it seems Flutter didn't expose it although I see such `SRCROOT=....` in build logs.

**Describe the solution you'd like**

1. let users to install conan
2. call `conan build` in cached opencv_dart package directory to build libs
3. copy build libs to corresponding platform directory (already implemented in conanfile.py)

**Additional context**

- #75

**Comment by rainyl** [comment]
1. yes, only wrappers will be built.

2. have you set OPENCV_DART_ARCH environment variable? by default arm64 will be built.

**Comment by rainyl** [comment]
Well, maybe we should make the default ARCH=x64 instead of arm64?

**Comment by abdelaziz-mahdy** [comment]
> Well, maybe we should make the default ARCH=x64 instead of arm64?

Let me test it , can't we make it a universal framework? Where are the framework built for iOS.to try to do so

**Comment by abdelaziz-mahdy** [comment]
> 1. yes, only wrappers will be built. ~~allow me to explain it later~~. As you said, building opencv itself is time consuming, that's why I moved it to `opencv.full` to prebuild it, but building wrappers is fast, so I think build them locally is better, and in this way it will be convenient to add more atchtectures like linux aarch64, because it doesn't need a prebuild.
> 
> 2. have you set OPENCV_DART_ARCH environment variable? by default arm64 will be built, I have no apple devices so not sure whether arm64 or x64 simulator will be used on arm64 macos? I will test it on x64 hackintosh, thanks~
> 
> 

I think the simulation is arm too but will check again

**Comment by rainyl** [comment]
> > Well, maybe we should make the default ARCH=x64 instead of arm64?
> 
> Let me test it , can't we make it a universal framework? Where are the framework built for iOS.to try to do so

Will a universal framework produce a large app after distribution? If not I think we can try to make it universal.

> I think the simulation is arm too but will check again

Thanks~

**Comment by rainyl** [comment]
It's so annoying to process native libs distribution for dart, especially for ios, x64, arm64, arm64 simulator...., enough! I do not use iphone even not an apple user, so not expert in apple developement, and I have waste several days on solving ios releated problems.

So I decide to revert to download from releases, just as #66 but with fixed working directory.

**Comment by abdelaziz-mahdy** [comment]
> It's so annoying to process native libs distribution for dart, especially for ios, x64, arm64, arm64 simulator...., enough! I do not use iphone even not an apple user, so not expert in apple developement, and I have waste several days on solving ios releated problems.
> 
> So I decide to revert to download from releases, just as #66 but with fixed working directory.

note: the problem with simualtor does happen using setup command too without the local build, just to be clear
https://github.com/rainyl/opencv_dart/pull/66#issuecomment-2137153646
so the ios covering all archs option will be the best bet

**Comment by rainyl** [comment]
> so the ios covering all archs option will be the best bet

Yes, it is in consideration too, almost finished :)
