### ISSUE TITLE
clone required for feature call

### ISSUE THREAD

**Issue by abdelaziz-mahdy** [rainyl/opencv_dart#95]
i think clone should be added to c++ wrapper https://github.com/abdelaziz-mahdy/face_grouping/commit/544bc95202805f9fbe4615c6f9cb8638db05583b since if not called in dart it will override the value of other mats i took alot of time to debug this problem

should be added in wrapper or not is the question?

**Comment by rainyl** [comment]
> i think clone should be added to c++ wrapper

Mat.clone() actually calls the c++ wrapper. https://github.com/rainyl/opencv_dart/blob/19ab8628a41439048e8ecf53d9cce90b8d27cdcc/lib/src/core/mat.dart#L1166-L1171

https://github.com/rainyl/opencv_dart/blob/19ab8628a41439048e8ecf53d9cce90b8d27cdcc/src/core/core.cpp#L147-L152

> since if not called in dart it will override the value of other mats i took alot of time to debug this problem

I am not clear about what exactly you mean "if not called in dart it will override the value of other mats" , does it means the current clone will corrupt the data of other mats?

**Comment by abdelaziz-mahdy** [comment]
i meant that for `FaceRecognizerSF` feature call any other call will override the prev mat data, so i need to call clone from dart side, should we make the wrapper auto call clone to avoid that bug?

**Comment by rainyl** [comment]
Okay, I will take a look at it, but theretically every time the feature() is called, a new Mat will be created... not sure why.

**Comment by rainyl** [comment]
confirmed, it seems to be a bug of wrong pointer, i will locate and fix it recently.

**Comment by abdelaziz-mahdy** [comment]
> confirmed, it seems to be a bug of wrong pointer, i will locate and fix it recently.

An easy and sufficient fix is cloning the mat and return the cloned mat, don't know if it's safe and memory safe or not

**Comment by rainyl** [comment]
Oh... I just noticed that the tutorial of opencv also manually clones the features
![image](https://github.com/rainyl/opencv_dart/assets/30213663/ff21cf2c-d7fe-4e91-b7fb-d21f5ee14b9b)
I am not sure why they design it that way but I think keeping the same behavior as official opencv is better, I can add an optional parameter as following to allow deep copying, which will be passed to C++ wrappers and clone in C++ side.

```dart
Mat feature(Mat alignedImg, {bool clone = false})
```

**Comment by rainyl** [comment]
@abdelaziz-mahdy I have published v1.0.8, you can update and try whether it works, if the problem still exists, please reopen this issue. 😄

**Comment by abdelaziz-mahdy** [comment]
Will check and let you know if there is a problem thank you ❤️
